export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";

// Hit by a system crontab entry every few minutes, same pattern as
// cron/instagram-publish — a shared-secret-protected endpoint with no user
// session, not meant to be called from the browser.
//
// Only "stale_deal"/"no_activity_days" triggers with a "create_task" action
// actually do anything in this phase — send_notification/notify_crm_agent
// are rejected at rule-creation time (see automation-rules/route.ts) since
// there's no notification channel or CRM Agent built yet to back them.
export async function GET(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get("secret");
  if (!secret || secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const rules = await prisma.crmAutomationRule.findMany({
    where: { isActive: true, trigger: { in: ["stale_deal", "no_activity_days"] }, action: "create_task" },
  });

  let tasksCreated = 0;
  const errors: string[] = [];

  for (const rule of rules) {
    try {
      let days = 3;
      try {
        const parsed = JSON.parse(rule.condition || "{}");
        if (Number.isFinite(parsed.days) && parsed.days > 0) days = parsed.days;
      } catch { /* keep default */ }

      const threshold = new Date(Date.now() - days * 24 * 60 * 60 * 1000);

      const staleDeals = await prisma.crmDeal.findMany({
        where: { userId: rule.userId, status: "open", updatedAt: { lt: threshold } },
        include: { contact: { select: { id: true, name: true } } },
      });

      for (const deal of staleDeals) {
        // Dedupe by task title so re-running the cron doesn't spam a new task
        // for the same stale deal every few minutes.
        const title = `[${rule.name}] پیگیری معامله «${deal.title}»`;
        const alreadyExists = await prisma.crmTask.findFirst({
          where: { userId: rule.userId, contactId: deal.contactId, title, status: "pending" },
        });
        if (alreadyExists) continue;

        await prisma.crmTask.create({
          data: { userId: rule.userId, contactId: deal.contactId, title, autoGenerated: true },
        });
        tasksCreated++;
      }
    } catch (err) {
      errors.push(`rule ${rule.id}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return NextResponse.json({ rulesEvaluated: rules.length, tasksCreated, errors });
}
