import {beforeAll,afterAll,beforeEach,describe,it,expect,vi} from "vitest";
import {mkdir,writeFile} from "node:fs/promises";
import {randomUUID} from "node:crypto";
import {NextRequest} from "next/server";
const {model}=vi.hoisted(()=>({model:vi.fn()}));
vi.mock("@/lib/ai/router",()=>({routedStreamChat:model}));
// Keep academy journeys deterministic while pricing-configuration suites mutate shared settings.
// Configurable production pricing itself is covered by generation.integration.test.ts.
vi.mock("@/lib/utils/creditCosts",async()=>{const {CREDIT_COSTS,TOOL_COST_DEFAULTS}=await import("@/lib/utils/credits");return {getCreditCosts:async()=>({...CREDIT_COSTS,...TOOL_COST_DEFAULTS})};});
import {prisma} from "@/lib/db/prisma";
import {enroll,learningVersion,validateCompletion,verifyCertificate,snapshotPublished} from "./academy";
import {saveCourseProgress} from "./learning";
import {queueFragment,applyFragment} from "./regeneration";
import {courseContentSchema} from "./content";
import {generateCourse,processQueuedCourseJobs,approveBlueprint,failCourseJob} from "./generation";
import {GET as catalog} from "@/app/api/learn/courses/route";
import {POST as majorCreate} from "@/app/api/admin/academy/majors/route";
import {PATCH as userProfile} from "@/app/api/user/profile/route";
import {PATCH as academicProfile} from "@/app/api/student/academic-profile/route";
import {POST as reissue,PATCH as revoke} from "@/app/api/admin/academy/certificates/route";
import {POST as progressApi} from "@/app/api/learn/courses/[id]/progress/route";
import {GET as certificateDownload} from "@/app/api/learn/courses/[id]/certificate/route";
import {GET as readNote,PUT as writeNote} from "@/app/api/learn/courses/[id]/notes/route";
import {POST as restoreRevision} from "@/app/api/admin/ai-courses/[id]/revisions/route";
import {PATCH as editCourse} from "@/app/api/admin/ai-courses/[id]/route";
import {GET as lessonApi} from "@/app/api/learn/courses/[id]/lesson/route";
import {POST as enrollApi} from "@/app/api/learn/courses/[id]/enroll/route";
import {signToken} from "@/lib/auth/jwt";
const question={question:"Which action correctly applies the approved course principle?",options:["Use validated data","Trust arbitrary client input","Skip all validation","Invent completion"],correctIndex:0,explanation:"The approved principle requires authoritative validated data."};
const lesson={title:"Validated application",content:"Validate all input and derive completion from authoritative data. A concrete example applies this principle to a course workflow. ".repeat(3),blocks:[{type:"heading",text:"Validated application"},{type:"paragraph",text:"Use validated authoritative records."},{type:"example",text:"A passing attempt must be recorded before completion."},{type:"knowledgeCheck",prompt:"What data is authoritative?",answer:"Server records."}],activity:"Implement a small example that validates input and calculates a result.",quiz:[question]};
const content={overview:"Practical education with verified server-side activities and concrete examples.",objectives:["Validate authoritative records","Apply the principles in practice","Evaluate the resulting implementation"],chapters:[0,1,2].map(i=>({title:`Module ${i+1}`,lessons:[{...lesson,title:`Lesson ${i+1}`}]})),finalProject:{title:"Verified implementation",instructions:"Build a complete example using the course principles, explain your design and document validation, testing and limitations. Demonstrate the result with reproducible examples.",rubric:["Applies the approved course principles","Documents reproducible examples and tests","Explains limitations of the resulting work"]},finalAssessment:[question,question,question]};
describe.runIf(process.env.RUN_BANK_INTEGRATION==="1")("Academy verified learning",()=>{
 const users:string[]=[],courses:string[]=[],majors:string[]=[];
 const req=(id:string,body?:unknown,url="https://aifekr.test/api/learn/courses")=>new NextRequest(url,{method:body?"POST":"GET",headers:{cookie:`token=${signToken({userId:id,role:"USER",plan:"STUDENT_FIRST_THREE_MONTHS"})}`,"content-type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});
 async function user(role="USER"){const u=await prisma.user.create({data:{name:"Test Student",email:`academy-${randomUUID()}@test.invalid`,role,credits:350,aiCredits:350,accountType:"STUDENT",plan:"STUDENT_FIRST_THREE_MONTHS",planExpiry:new Date(Date.now()+86400000)}});users.push(u.id);return u;}
 async function course(publish=true){const c=await prisma.aiCourse.create({data:{creatorId:users[0],title:"React Development",fieldOfStudy:"Software Engineering",description:"Practical React course for software engineering students with validated assessments.",content:JSON.stringify(content),version:1,status:publish?"PUBLISHED":"GENERATED",configuration:JSON.stringify({requirements:{lessonPercent:100,quizScore:70,finalRequired:true,finalScore:75,attemptLimit:3}})}});courses.push(c.id);if(publish)await prisma.$transaction(tx=>snapshotPublished(tx,c));return c;}
 beforeAll(async()=>{if(process.env.DATABASE_URL!=="file:./vitest.db")throw Error("Isolated DB required");await user("ADMIN");});
 beforeEach(()=>{model.mockReset();model.mockImplementation(async(_m,system,chunk)=>{chunk(JSON.stringify(system.includes("only the outline")?{...content,chapters:content.chapters.map(c=>({title:c.title,lessons:c.lessons.map(l=>l.title)}))}:system.includes("final assessment questions")?{questions:content.finalAssessment}:lesson));return {id:"test",model:"test"};});});
 afterAll(async()=>{const completions=await prisma.aiCourseCompletion.findMany({where:{courseId:{in:courses}},select:{id:true}});await prisma.aiCourseCertificate.deleteMany({where:{completionId:{in:completions.map(c=>c.id)}}});await prisma.aiCourseCompletion.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourseAssessmentAttempt.deleteMany({where:{userId:{in:users}}});await prisma.aiCourseProgress.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourseGenerationJob.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourseLessonNote.deleteMany({where:{userId:{in:users}}});await prisma.aiCourseRevision.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourse.updateMany({where:{id:{in:courses}},data:{publishedVersionId:null}});await prisma.aiCourseVersion.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourseMajor.deleteMany({where:{courseId:{in:courses}}});await prisma.aiCourse.deleteMany({where:{id:{in:courses}}});await prisma.studentAcademicProfile.deleteMany({where:{userId:{in:users}}});await prisma.academicSpecialization.deleteMany({where:{majorId:{in:majors}}});await prisma.academicMajor.deleteMany({where:{id:{in:majors}}});await prisma.auditLog.deleteMany({where:{actorId:{in:users}}});await prisma.usageLog.deleteMany({where:{userId:{in:users}}});await prisma.errorLog.deleteMany({where:{userId:{in:users},source:"ai-course-generation"}});await prisma.user.deleteMany({where:{id:{in:users}}});});
 it("requires enrollment, passing attempts and final assessment before verified issuance",async()=>{const u=await user(),c=await course();const e=await enroll(u.id,c.id);await expect(saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"complete"})).rejects.toMatchObject({code:"PASS_LESSON_QUIZ_FIRST"});for(let i=0;i<3;i++){await saveCourseProgress(u.id,c.id,{lessonId:`${i}:0`,action:"quiz",answers:[0]});await saveCourseProgress(u.id,c.id,{lessonId:`${i}:0`,action:"complete"});}expect(await prisma.aiCourseCompletion.count({where:{enrollmentId:e.id}})).toBe(0);const fail=await saveCourseProgress(u.id,c.id,{lessonId:"final",action:"quiz",answers:[0,0,1]});expect(fail.result?.passed).toBe(false);expect(await prisma.aiCourseCompletion.count({where:{enrollmentId:e.id}})).toBe(0);await saveCourseProgress(u.id,c.id,{lessonId:"final",action:"quiz",answers:[0,0,0]});const complete=await prisma.aiCourseCompletion.findUniqueOrThrow({where:{enrollmentId:e.id},include:{certificate:true}});expect(complete.score).toBe(100);expect(complete.certificate?.verificationCode).toHaveLength(48);await saveCourseProgress(u.id,c.id,{lessonId:"2:0",action:"complete"});expect(await prisma.aiCourseCompletion.count({where:{enrollmentId:e.id}})).toBe(1);expect((await prisma.user.findUniqueOrThrow({where:{id:u.id}})).credits).toBe(350);});
 it("forged frontend progress cannot create a verified completion",async()=>{const u=await user(),c=await course(),e=await enroll(u.id,c.id);await prisma.aiCourseProgress.update({where:{id:e.id},data:{completed:'["0:0","1:0","2:0"]',quizPassed:'["0:0","1:0","2:0"]',finalPassed:true}});expect(await prisma.$transaction(tx=>validateCompletion(tx,e.id))).toBeNull();const response=await progressApi(req(u.id,{lessonId:"0:0",action:"complete",requestKey:randomUUID(),progress:100,completedAt:new Date().toISOString()}),{params:{id:c.id}});expect(response.status).toBe(400);expect(await prisma.aiCourseCertificate.count({where:{completion:{userId:u.id}}})).toBe(0);});
 it("permanent attempts are idempotent and enforce configured limits",async()=>{const u=await user(),c=await course(),e=await enroll(u.id,c.id),key=randomUUID();await saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"quiz",answers:[1],requestKey:key});await saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"quiz",answers:[1],requestKey:key});expect(await prisma.aiCourseAssessmentAttempt.count({where:{enrollmentId:e.id}})).toBe(1);await expect(saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"quiz",answers:[0],requestKey:key})).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"});for(let i=0;i<2;i++)await saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"quiz",answers:[1]});await expect(saveCourseProgress(u.id,c.id,{lessonId:"0:0",action:"quiz",answers:[0]})).rejects.toMatchObject({code:"ATTEMPT_LIMIT_REACHED"});});
 it("enrolled version survives publication changes and archival",async()=>{const u=await user(),c=await course();const e=await enroll(u.id,c.id);await prisma.aiCourse.update({where:{id:c.id},data:{publishedVersionId:null,version:2,title:"Changed title",content:JSON.stringify({...content,overview:"A substantially changed course introduction with new requirements."}),status:"ARCHIVED"}});const bound=await learningVersion(u.id,c.id);expect(bound.version.version).toBe(1);expect(bound.version.title).toBe("React Development");expect(bound.enrollment?.id).toBe(e.id);const other=await user();await expect(enroll(other.id,c.id)).rejects.toMatchObject({code:"COURSE_NOT_FOUND"});});
 it("student selects normalized major and receives mapped recommendations",async()=>{const admin=await user("ADMIN"),u=await user(),c=await course();const r=await majorCreate(req(admin.id,{name:"Software Engineering",slug:`software-${randomUUID()}`,specializations:["Frontend"]}));expect(r.status).toBe(200);const m=(await r.json()).major;majors.push(m.id);expect((await academicProfile(req(u.id,{majorId:m.id}))).status).toBe(200);await prisma.aiCourseMajor.create({data:{courseId:c.id,majorId:m.id}});const cat=await catalog(req(u.id));expect((await cat.json()).courses.find((x:{id:string})=>x.id===c.id).recommended).toBe(true);expect((await majorCreate(req(u.id,{name:"Forbidden",slug:"forbidden"}))).status).toBe(403);expect((await academicProfile(req(u.id,{majorId:"missing"}))).status).toBe(400);});
 it("blueprint approval shares one 100-credit reservation with full generation",async()=>{const admin=await user("ADMIN"),c=await prisma.aiCourse.create({data:{creatorId:admin.id,title:"React Development",fieldOfStudy:"Software Engineering",description:"Practical React course with structured lessons and a complete final assessment.",configuration:JSON.stringify({requirements:{finalRequired:true}})}});courses.push(c.id);const job=await generateCourse(admin.id,c.id,{idempotencyKey:randomUUID(),expectedCredits:100,phase:"BLUEPRINT"});expect(job.status).toBe("QUEUED_BLUEPRINT");expect(model).not.toHaveBeenCalled();await processQueuedCourseJobs();const blueprint=await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}});expect(blueprint.status).toBe("BLUEPRINT_REVIEW");expect(blueprint.content).toBeNull();await approveBlueprint(admin.id,c.id,JSON.parse(blueprint.blueprint!));await processQueuedCourseJobs();expect((await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:job.id}})).status).toBe("SUCCEEDED");expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(250);expect((await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}})).status).toBe("GENERATED");});
 it("retries approved failed generation without discarding validated lesson checkpoints",async()=>{const admin=await user("ADMIN"),c=await course(false);const first=await generateCourse(admin.id,c.id,{idempotencyKey:randomUUID(),expectedCredits:100,phase:"BLUEPRINT",regenerate:true,confirmRegeneration:true});await processQueuedCourseJobs();const draft=await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}});await approveBlueprint(admin.id,c.id,JSON.parse(draft.blueprint!));const approved=await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:first.id}});await prisma.aiCourseGenerationJob.update({where:{id:first.id},data:{checkpoint:JSON.stringify({...JSON.parse(approved.checkpoint),"0:0":lesson})}});await failCourseJob(first.id,"GENERATION_TIMEOUT");model.mockClear();const retry=await generateCourse(admin.id,c.id,{idempotencyKey:randomUUID(),expectedCredits:100,phase:"BLUEPRINT",regenerate:true,confirmRegeneration:true});expect(retry.status).toBe("QUEUED_CONTENT");await processQueuedCourseJobs();expect(model).toHaveBeenCalledTimes(3);expect((await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:retry.id}})).status).toBe("SUCCEEDED");expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(250);});
 it("large course generation continues in bounded jobs with one reservation",async()=>{const admin=await user("ADMIN"),c=await course(false),blueprint={...content,chapters:content.chapters.map((ch,ci)=>({title:ch.title,lessons:[0,1,2].map(li=>`Lesson ${ci+1}.${li+1}`)}))};model.mockImplementation(async(_m,system,chunk)=>{chunk(JSON.stringify(system.includes("only the outline")?blueprint:system.includes("final assessment questions")?{questions:content.finalAssessment}:{...lesson,title:JSON.parse(_m[0].content).lesson}));return {id:"test",model:"test"};});const job=await generateCourse(admin.id,c.id,{idempotencyKey:randomUUID(),expectedCredits:100,phase:"BLUEPRINT",regenerate:true,confirmRegeneration:true});await processQueuedCourseJobs();await approveBlueprint(admin.id,c.id,blueprint);await processQueuedCourseJobs();const partial=await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:job.id}});expect(partial.status).toBe("QUEUED_CONTENT");expect(Object.keys(JSON.parse(partial.checkpoint)).filter(k=>/^\d+:\d+$/.test(k))).toHaveLength(8);expect((await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}})).content).toBe(c.content);await processQueuedCourseJobs();expect((await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:job.id}})).status).toBe("SUCCEEDED");expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(250);expect(await prisma.usageLog.count({where:{userId:admin.id,type:"course_generation"}})).toBe(1);});
 it("published learning remains available while the administrator edits a new draft",async()=>{const admin=await user("ADMIN"),student=await user(),c=await course();expect((await editCourse(req(admin.id,{version:c.version,title:"Unpublished draft title"}),{params:{id:c.id}})).status).toBe(200);const original=await learningVersion(student.id,c.id);expect(original.version.title).toBe("React Development");expect((await enroll(student.id,c.id)).version).toBe(1);const found=await catalog(req(student.id,undefined,"https://aifekr.test/api/learn/courses?search=React"));expect((await found.json()).courses.find((x:{id:string})=>x.id===c.id).title).toBe("React Development");const draft=await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}});expect((await editCourse(req(admin.id,{version:draft.version,status:"UNPUBLISHED"}),{params:{id:c.id}})).status).toBe(200);const other=await user();await expect(enroll(other.id,c.id)).rejects.toMatchObject({code:"COURSE_NOT_FOUND"});expect((await learningVersion(student.id,c.id)).version.version).toBe(1);});
 it("cancelling the reviewed blueprint refunds the reservation once",async()=>{const admin=await user("ADMIN"),c=await course(false);const job=await generateCourse(admin.id,c.id,{idempotencyKey:randomUUID(),expectedCredits:100,phase:"BLUEPRINT",regenerate:true,confirmRegeneration:true});await processQueuedCourseJobs();await failCourseJob(job.id,"CANCELLED_BY_ADMIN");await failCourseJob(job.id,"CANCELLED_BY_ADMIN");expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(350);});
 it("verification reveals only certificate presentation fields and audited revocation persists",async()=>{const admin=await user("ADMIN"),u=await user(),other=await user(),c=await course();for(let i=0;i<3;i++){await saveCourseProgress(u.id,c.id,{lessonId:`${i}:0`,action:"quiz",answers:[0]});await saveCourseProgress(u.id,c.id,{lessonId:`${i}:0`,action:"complete"});}await saveCourseProgress(u.id,c.id,{lessonId:"final",action:"quiz",answers:[0,0,0]});const cert=await prisma.aiCourseCertificate.findFirstOrThrow({where:{completion:{userId:u.id}}});const pdf=await certificateDownload(req(u.id),{params:{id:c.id}});expect(pdf.status).toBe(200);const bytes=Buffer.from(await pdf.arrayBuffer());expect(bytes.subarray(0,4).toString()).toBe("%PDF");await mkdir("output/pdf",{recursive:true});await writeFile("output/pdf/academy-certificate-qa.pdf",bytes);const verified=await verifyCertificate(cert.verificationCode);expect(verified?.status).toBe("ACTIVE");expect(verified).not.toHaveProperty("userId");expect(verified).not.toHaveProperty("email");expect(await verifyCertificate("fabricated")).toBeNull();expect((await certificateDownload(req(other.id),{params:{id:c.id}})).status).toBe(404);expect((await reissue(req(u.id,{id:cert.id,reason:"Replace the previously downloaded file",confirm:true}))).status).toBe(403);expect((await reissue(req(admin.id,{id:cert.id,reason:"Replace the previously downloaded file",confirm:true}))).status).toBe(200);expect(await prisma.auditLog.count({where:{targetId:cert.id,action:"academy_certificate_reissued"}})).toBe(1);expect((await revoke(req(u.id,{id:cert.id,reason:"Unauthorized revocation attempt"}))).status).toBe(403);expect((await revoke(req(admin.id,{id:cert.id,reason:"Certificate issued against incorrect identity"}))).status).toBe(200);expect((await verifyCertificate(cert.verificationCode))?.status).toBe("REVOKED");expect((await reissue(req(admin.id,{id:cert.id,reason:"Must not reactivate revoked certificate",confirm:true}))).status).toBe(410);expect((await certificateDownload(req(u.id),{params:{id:c.id}})).status).toBe(410);expect(await prisma.auditLog.count({where:{targetId:cert.id,action:"academy_certificate_revoked"}})).toBe(1);});
 it("selective regeneration has its own cost, preview and free audited apply",async()=>{const admin=await user("ADMIN"),c=await course();model.mockImplementation(async(_m,_s,chunk)=>{chunk(JSON.stringify({overview:"An improved approved university course overview with practical applications."}));return {id:"test",model:"test"};});const input={action:"description" as const,version:c.version,idempotencyKey:randomUUID(),expectedCredits:2};const job=await queueFragment(admin.id,c.id,input);expect((await queueFragment(admin.id,c.id,input)).id).toBe(job.id);await processQueuedCourseJobs();expect((await prisma.aiCourseGenerationJob.findUniqueOrThrow({where:{id:job.id}})).status).toBe("PREVIEW_READY");expect((await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}})).content).toBe(c.content);expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(348);await applyFragment(admin.id,c.id,job.id);expect((await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}})).status).toBe("GENERATED");expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(348);await expect(applyFragment(admin.id,c.id,job.id)).rejects.toMatchObject({code:"PREVIEW_NOT_READY"});expect(await prisma.auditLog.count({where:{targetId:c.id,action:"academy_regeneration_applied"}})).toBe(1);});
 it("search cannot expose drafts to another student",async()=>{const u=await user(),c=await course(false);const r=await catalog(req(u.id,undefined,"https://aifekr.test/api/learn/courses?search=React"));expect((await r.json()).courses.some((x:{id:string})=>x.id===c.id)).toBe(false);});
 it("private notes persist across reads, remain isolated and cost no credits",async()=>{const u=await user(),other=await user(),c=await course();await enroll(u.id,c.id);const url="https://aifekr.test/notes?lesson=0:0";expect((await writeNote(req(u.id,{content:"My private learning notes"},url),{params:{id:c.id}})).status).toBe(200);expect((await (await readNote(req(u.id,undefined,url),{params:{id:c.id}})).json()).note.content).toBe("My private learning notes");await enroll(other.id,c.id);expect((await (await readNote(req(other.id,undefined,url),{params:{id:c.id}})).json()).note).toBeNull();expect((await writeNote(req(other.id,{content:"Forged",userId:u.id},url),{params:{id:c.id}})).status).toBe(400);expect((await prisma.user.findUniqueOrThrow({where:{id:u.id}})).credits).toBe(350);});
 it("draft history restoration is privileged, audited, free and preserves enrollment version",async()=>{const admin=await user("ADMIN"),u=await user(),c=await course();const e=await enroll(u.id,c.id);expect((await editCourse(req(admin.id,{version:c.version,title:"Edited course title"}),{params:{id:c.id}})).status).toBe(200);const revision=await prisma.aiCourseRevision.findFirstOrThrow({where:{courseId:c.id}}),body={revisionId:revision.id,version:c.version+1,confirm:true};expect((await restoreRevision(req(u.id,body),{params:{id:c.id}})).status).toBe(403);expect((await restoreRevision(req(admin.id,body),{params:{id:c.id}})).status).toBe(200);const restored=await prisma.aiCourse.findUniqueOrThrow({where:{id:c.id}});expect(restored.title).toBe(c.title);expect(restored.status).toBe("GENERATED");expect(restored.version).toBe(c.version+2);expect((await learningVersion(u.id,c.id)).enrollment?.id).toBe(e.id);expect((await prisma.user.findUniqueOrThrow({where:{id:admin.id}})).credits).toBe(350);});
 it("learning-path prerequisites require distinct verified courses while independent enrollment stays available",async()=>{const u=await user(),a=await course(),b=await course(),c=await course();const path=await prisma.academyLearningPath.create({data:{title:"Verified learning path",status:"PUBLISHED",courses:JSON.stringify([{courseId:a.id,requiredBeforeNext:true},{courseId:b.id,requiredBeforeNext:true},{courseId:c.id,requiredBeforeNext:false}])}});try{expect((await enrollApi(req(u.id,{pathId:path.id}),{params:{id:c.id}})).status).toBe(409);for(const current of [a,b]){for(let i=0;i<3;i++){await saveCourseProgress(u.id,current.id,{lessonId:`${i}:0`,action:"quiz",answers:[0]});await saveCourseProgress(u.id,current.id,{lessonId:`${i}:0`,action:"complete"});}await saveCourseProgress(u.id,current.id,{lessonId:"final",action:"quiz",answers:[0,0,0]});}expect((await enrollApi(req(u.id,{pathId:path.id}),{params:{id:c.id}})).status).toBe(200);const other=await user();expect((await enrollApi(req(other.id,{}),{params:{id:c.id}})).status).toBe(200);}finally{await prisma.academyLearningPath.delete({where:{id:path.id}});}});
 it("randomized advanced question banks hide keys, enforce signed selection and persist answers",async()=>{const u=await user(),c=await course(false),bank=[{type:"trueFalse",question:"Authoritative records determine progress.",correct:true,explanation:"Only backend records determine course progress."},{type:"shortAnswer",question:"Name the source of authoritative completion data.",acceptedAnswers:["server"],caseSensitive:false,explanation:"The server validates authoritative completion data."}];const source={...content,chapters:content.chapters.map((ch,i)=>i?ch:{...ch,lessons:[{...ch.lessons[0],assessmentQuestions:bank,assessmentSettings:{randomize:true,questionCount:1}}]})};const published=await prisma.aiCourse.update({where:{id:c.id},data:{status:"PUBLISHED",content:JSON.stringify(source)}});await prisma.$transaction(tx=>snapshotPublished(tx,published));await enroll(u.id,c.id);const response=await lessonApi(req(u.id,undefined,`https://aifekr.test/lesson?lesson=0:0`),{params:{id:c.id}}),data=await response.json();expect(response.status).toBe(200);expect(data.lesson.quiz).toHaveLength(1);expect(data.lesson.quiz[0]).not.toHaveProperty("correct");expect(data.lesson.quiz[0]).not.toHaveProperty("acceptedAnswers");const answers=[data.lesson.quiz[0].type==="trueFalse"?true:"SERVER"],body={lessonId:"0:0",action:"quiz",requestKey:randomUUID(),answers,assessmentToken:data.lesson.assessmentToken};expect((await progressApi(req(u.id,{...body,assessmentToken:body.assessmentToken+"x"}),{params:{id:c.id}})).status).toBe(409);expect((await progressApi(req(u.id,body),{params:{id:c.id}})).status).toBe(200);const attempt=await prisma.aiCourseAssessmentAttempt.findFirstOrThrow({where:{userId:u.id,assessmentId:"0:0"}});expect(attempt.score).toBe(100);expect(JSON.parse(attempt.answers).indices).toHaveLength(1);expect((await prisma.user.findUniqueOrThrow({where:{id:u.id}})).credits).toBe(350);});
 it.each(["fa","en","de","tr"])("post-registration language %s persists in the account and cookie",async(language)=>{const u=await user(),response=await userProfile(req(u.id,{language}));expect(response.status).toBe(200);expect(response.headers.get("set-cookie")).toContain(`lang=${language}`);expect((await prisma.user.findUniqueOrThrow({where:{id:u.id}})).language).toBe(language);});
 it("rejects duplicate chapters, unsupported blocks and dangerous media protocols",()=>{expect(()=>courseContentSchema.parse({...content,chapters:[content.chapters[0],content.chapters[0],content.chapters[2]]})).toThrow();expect(()=>courseContentSchema.parse({...content,chapters:[...content.chapters.slice(1),{title:"Unsafe",lessons:[{...lesson,blocks:[{type:"html",text:"<script>"},{type:"image",url:"javascript:alert(1)",alt:"Unsafe"}]}]}]})).toThrow();});
});
