import {z} from "zod";
export const assessmentSettings=z.object({randomize:z.boolean().default(true),questionCount:z.number().int().min(1).max(30).optional()});
const text=z.string().trim().min(1).max(2000),common={question:text,explanation:text};
export const academyQuestion=z.discriminatedUnion("type",[
 z.object({...common,type:z.literal("multipleChoice"),options:z.array(text).min(2).max(12),correctIndex:z.number().int().min(0).max(11)}),
 z.object({...common,type:z.literal("multipleSelect"),options:z.array(text).min(2).max(12),correctIndices:z.array(z.number().int().min(0).max(11)).min(1).max(12)}),
 z.object({...common,type:z.literal("trueFalse"),correct:z.boolean()}),
 z.object({...common,type:z.literal("shortAnswer"),acceptedAnswers:z.array(text).min(1).max(20),caseSensitive:z.boolean().default(false)}),
 z.object({...common,type:z.literal("ordering"),items:z.array(text).min(2).max(12),correctOrder:z.array(z.number().int().min(0).max(11)).min(2).max(12)}),
 z.object({...common,type:z.literal("matching"),left:z.array(text).min(2).max(12),right:z.array(text).min(2).max(12),correctMatches:z.array(z.number().int().min(0).max(11)).min(2).max(12)}),
]).superRefine((q,ctx)=>{const invalid=()=>ctx.addIssue({code:"custom",message:"Invalid answer mapping"});if(q.type==="multipleChoice"&&q.correctIndex>=q.options.length)invalid();if(q.type==="multipleSelect"&&(new Set(q.correctIndices).size!==q.correctIndices.length||q.correctIndices.some(i=>i>=q.options.length)))invalid();if(q.type==="ordering"&&(q.correctOrder.length!==q.items.length||new Set(q.correctOrder).size!==q.items.length||q.correctOrder.some(i=>i>=q.items.length)))invalid();if(q.type==="matching"&&(q.left.length!==q.right.length||q.correctMatches.length!==q.left.length||new Set(q.correctMatches).size!==q.left.length||q.correctMatches.some(i=>i>=q.right.length)))invalid();});
export type AcademyQuestion=z.infer<typeof academyQuestion>;
export type QuizAnswer=number|number[]|string|boolean;
export function publicQuestion(q:AcademyQuestion){switch(q.type){case "multipleChoice":case "multipleSelect":return {type:q.type,question:q.question,options:q.options};case "trueFalse":case "shortAnswer":return {type:q.type,question:q.question};case "ordering":return {type:q.type,question:q.question,items:q.items};case "matching":return {type:q.type,question:q.question,left:q.left,right:q.right};}}
export type PublicQuestion=ReturnType<typeof publicQuestion>;
export function answerValid(q:AcademyQuestion,a:QuizAnswer){switch(q.type){case "multipleChoice":return Number.isInteger(a)&&typeof a==="number"&&a>=0&&a<q.options.length;case "multipleSelect":return Array.isArray(a)&&a.length>0&&new Set(a).size===a.length&&a.every(i=>Number.isInteger(i)&&i>=0&&i<q.options.length);case "trueFalse":return typeof a==="boolean";case "shortAnswer":return typeof a==="string"&&a.trim().length>0&&a.length<=2000;case "ordering":return Array.isArray(a)&&a.length===q.items.length&&new Set(a).size===a.length&&a.every(i=>Number.isInteger(i)&&i>=0&&i<q.items.length);case "matching":return Array.isArray(a)&&a.length===q.left.length&&new Set(a).size===a.length&&a.every(i=>Number.isInteger(i)&&i>=0&&i<q.right.length);}}
export function answerCorrect(q:AcademyQuestion,a:QuizAnswer){if(!answerValid(q,a))return false;const equal=(x:number[],y:number[])=>JSON.stringify(x)===JSON.stringify(y);switch(q.type){case "multipleChoice":return a===q.correctIndex;case "multipleSelect":return equal([...(a as number[])].sort((a,b)=>a-b),[...q.correctIndices].sort((a,b)=>a-b));case "trueFalse":return a===q.correct;case "shortAnswer":{const normalize=(s:string)=>{const v=s.normalize("NFKC").trim().replace(/\s+/g," ");return q.caseSensitive?v:v.toLocaleLowerCase();};return q.acceptedAnswers.some(v=>normalize(v)===normalize(a as string));}case "ordering":return equal(a as number[],q.correctOrder);case "matching":return equal(a as number[],q.correctMatches);}}
export function legacyQuestions(questions:{question:string;options:string[];correctIndex:number;explanation:string}[]):AcademyQuestion[]{return questions.map(q=>({...q,type:"multipleChoice" as const}));}
