import {NextRequest,NextResponse} from "next/server";
import {requireAdmin,forbiddenResponse} from "@/lib/auth/middleware";
import {prisma} from "@/lib/db/prisma";
import {parseCourseContent,courseBrief} from "@/lib/courses/content";
import {preserveRevision} from "@/lib/courses/revisions";
import {snapshotPublished} from "@/lib/courses/academy";
import {z} from "zod";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest,{params}:{params:{id:string}}){if(!await requireAdmin(req))return forbiddenResponse();const id=req.nextUrl.searchParams.get("revision");if(id){const revision=await prisma.aiCourseRevision.findFirst({where:{id,courseId:params.id}});return revision?NextResponse.json({revision},{headers:{"Cache-Control":"private, no-store"}}):NextResponse.json({error:"NOT_FOUND"},{status:404});}return NextResponse.json({revisions:await prisma.aiCourseRevision.findMany({where:{courseId:params.id},select:{id:true,version:true,actorId:true,reason:true,createdAt:true},orderBy:{version:"desc"},take:100})},{headers:{"Cache-Control":"private, no-store"}});}
export async function POST(req:NextRequest,{params}:{params:{id:string}}){const admin=await requireAdmin(req);if(!admin)return forbiddenResponse();const input=z.object({revisionId:z.string(),version:z.number().int().min(0),confirm:z.literal(true)}).strict().safeParse(await req.json().catch(()=>null));if(!input.success)return NextResponse.json({error:"INVALID_RESTORE"},{status:400});try{return await prisma.$transaction(async tx=>{const c=await tx.aiCourse.findUniqueOrThrow({where:{id:params.id}});if(c.activeJobId||c.version!==input.data.version)return NextResponse.json({error:"COURSE_CHANGED_REFRESH"},{status:409});const r=await tx.aiCourseRevision.findFirstOrThrow({where:{id:input.data.revisionId,courseId:c.id}}),metadata=JSON.parse(r.metadata),content=parseCourseContent(r.content),brief=courseBrief.parse(metadata);await preserveRevision(tx,c,admin.id,"BEFORE_REVISION_RESTORE");if(c.status==="PUBLISHED")await snapshotPublished(tx,c);await tx.aiCourse.update({where:{id:c.id},data:{...brief,difficulty:metadata.difficulty,durationMinutes:metadata.durationMinutes,topic:metadata.topic,skills:metadata.skills,prerequisites:metadata.prerequisites,coverUrl:metadata.coverUrl,content:JSON.stringify(content),configuration:metadata.configuration,status:"GENERATED",publishedAt:null,version:{increment:1}}});await tx.auditLog.create({data:{actorId:admin.id,action:"academy_revision_restored",targetId:c.id,metadata:JSON.stringify({revisionId:r.id,sourceVersion:r.version,newVersion:c.version+1})}});return NextResponse.json({restored:true});});}catch{return NextResponse.json({error:"REVISION_RESTORE_FAILED"},{status:409});}}
