import type { Lang } from "@/lib/i18n/server";

export type Copy = readonly [string, string, string, string];
export const text = (lang: Lang, copy: Copy) => copy[({ fa: 0, en: 1, de: 2, tr: 3 } as const)[lang]];
export const copy = {
  product: ["محصول", "Product", "Produkt", "Ürün"],
  solutions: ["راهکارها", "Solutions", "Lösungen", "Çözümler"],
  industries: ["صنعت‌ها", "Industries", "Branchen", "Sektörler"],
  tools: ["ابزارهای AI", "AI tools", "KI-Tools", "Yapay zekâ araçları"],
  pricing: ["قیمت‌گذاری", "Pricing", "Preise", "Fiyatlar"],
  resources: ["منابع", "Resources", "Ressourcen", "Kaynaklar"],
  login: ["ورود", "Log in", "Anmelden", "Giriş"],
  start: ["شروع با AIFekr", "Start with AIFekr", "Mit AIFekr starten", "AIFekr ile başlayın"],
  explore: ["کشف قابلیت‌ها", "Explore the platform", "Plattform entdecken", "Platformu keşfedin"],
  demo: ["دموی نمایشی · بدون مصرف اعتبار", "Illustrative demo · no credits used", "Beispieldemo · kein Creditverbrauch", "Örnek demo · kredi kullanılmaz"],
  eyebrow: ["یک فضای متصل برای فکر، ساخت و رشد", "ONE CONNECTED SPACE TO THINK, CREATE & GROW", "EIN VERNETZTER RAUM FÜR IDEEN, KREATION & WACHSTUM", "DÜŞÜNMEK, ÜRETMEK VE BÜYÜMEK İÇİN TEK ALAN"],
  hero: ["هوش مصنوعی،\nدر جریان کار شما.", "AI, inside\nyour everyday work.", "KI, mitten in\nIhrem Arbeitsalltag.", "Yapay zekâ,\ngünlük işinizin içinde."],
  intro: ["از یک سؤال تا تولید محتوا، مدیریت مشتری و برنامهٔ مطالعه؛ ابزارهای هوش مصنوعی و فضای کاری‌تان را در AIFekr کنار هم داشته باشید.", "From a question to creating content, managing customers and planning your studies. Bring AI tools and your workspaces together in AIFekr.", "Von einer Frage über Inhalte und Kundenmanagement bis zum Lernplan. KI-Tools und Arbeitsbereiche gemeinsam in AIFekr.", "Bir sorudan içerik üretmeye, müşteri yönetimine ve çalışma planına. Yapay zekâ araçları ve çalışma alanları AIFekr'de bir arada."],
  noPromise: ["امکانات و دسترسی‌ها براساس پلن و ماژول فعال شما", "Access depends on your plan and enabled modules", "Zugriff abhängig von Tarif und aktivierten Modulen", "Erişim planınıza ve etkin modüllere bağlıdır"],
  ecosystem: ["ابزارهای جدا، یک جریان متصل.", "Different tools. One connected flow.", "Verschiedene Tools. Ein vernetzter Ablauf.", "Farklı araçlar. Tek bağlantılı akış."],
  ecosystemDesc: ["یک مسیر را انتخاب کنید و ببینید ابزارها چگونه به کار روزمره کمک می‌کنند.", "Choose a path to see how the tools support everyday work.", "Wählen Sie einen Weg und entdecken Sie die Unterstützung im Alltag.", "Bir yol seçin ve araçların günlük işlere nasıl yardımcı olduğunu görün."],
  workflow: ["از ایده تا اقدام، با کنترل شما.", "From an idea to action. With you in control.", "Von der Idee zur Aktion. Sie behalten die Kontrolle.", "Fikirden eyleme. Kontrol sizde."],
  workflowDesc: ["اطلاعات را وارد کنید، خروجی را بررسی کنید و در فضای مناسب ادامه دهید. اتصال حساب‌ها و فعال‌سازی ماژول‌ها اختیاری و وابسته به دسترسی شماست.", "Add your context, review the output and continue in the right workspace. Account connections and modules are optional and access-dependent.", "Kontext hinzufügen, Ergebnisse prüfen und im passenden Bereich fortfahren. Verbindungen und Module sind optional und zugriffsabhängig.", "Bilgilerinizi ekleyin, çıktıyı inceleyin ve uygun çalışma alanında devam edin. Hesap bağlantıları ve modüller isteğe ve erişime bağlıdır."],
  modules: ["فضای کاری شما، با ابزارهای مناسب شما.", "Your workspace. Your kind of tools.", "Ihr Arbeitsbereich. Ihre passenden Tools.", "Çalışma alanınız. Size uygun araçlar."],
  modulesDesc: ["برای هر کار، فضای مشخصی دارید؛ بدون گم‌شدن بین ابزارها.", "A dedicated space for each task, without losing your way between tools.", "Ein eigener Bereich für jede Aufgabe, ohne den Überblick zu verlieren.", "Araçlar arasında kaybolmadan, her görev için özel bir alan."],
  learn: ["آشنایی بیشتر", "Explore feature", "Funktion entdecken", "Özelliği keşfedin"],
  useCases: ["برای کار شما ساخته شده.", "Find your way of working.", "Finden Sie Ihren Arbeitsablauf.", "Çalışma şeklinizi bulun."],
  plansDesc: ["برای بیزنس یک اشتراک کافی است: تیم کامل AI، CRM و ابزارهای کسب‌وکار. ظرفیت مناسب خود را انتخاب کنید.", "One business subscription includes your AI team, CRM and business tools. Choose the capacity that fits you.", "Ein Business-Abo enthält KI-Team, CRM und Geschäftstools. Wählen Sie die passende Kapazität.", "Tek işletme aboneliği yapay zekâ ekibinizi, CRM ve işletme araçlarını içerir. Size uygun kapasiteyi seçin."],
  credits: ["اعتبار AI", "AI credits", "KI-Credits", "Yapay zekâ kredileri"],
  creditsDesc: ["مصرف به ابزار و مدل بستگی دارد. این اعداد، هزینهٔ تنظیم‌شدهٔ ابزارهای مشخص‌اند، نه هزینهٔ همهٔ مدل‌ها.", "Usage depends on the tool and model. These are configured costs for specific tools, not prices for every model.", "Verbrauch hängt von Tool und Modell ab. Diese Werte gelten für bestimmte Tools, nicht für alle Modelle.", "Kullanım araca ve modele bağlıdır. Bunlar belirli araçların yapılandırılmış maliyetleridir, tüm modellerin fiyatı değildir."],
  faq: ["قبل از شروع، بدانید.", "A few things before you start.", "Gut zu wissen, bevor Sie starten.", "Başlamadan önce bilmeniz gerekenler."],
  final: ["قدم بعدی‌تان را با AIFekr بردارید.", "Make your next move with AIFekr.", "Ihr nächster Schritt mit AIFekr.", "Bir sonraki adımınızı AIFekr ile atın."],
  about: ["دربارهٔ ما", "About", "Über uns", "Hakkımızda"],
  contact: ["تماس", "Contact", "Kontakt", "İletişim"],
  privacy: ["حریم خصوصی", "Privacy", "Datenschutz", "Gizlilik"],
  terms: ["شرایط استفاده", "Terms", "Bedingungen", "Koşullar"],
  security: ["داده‌ها و دسترسی", "Data & access", "Daten & Zugriff", "Veri ve erişim"],
  skip: ["رفتن به محتوا", "Skip to content", "Zum Inhalt", "İçeriğe geç"],
  menu: ["فهرست", "Menu", "Menü", "Menü"],
  back: ["بازگشت به قابلیت‌ها", "All features", "Alle Funktionen", "Tüm özellikler"],
  requirements: ["پیش‌نیازها و محدودیت‌ها", "Requirements & boundaries", "Voraussetzungen & Grenzen", "Gereksinimler ve sınırlar"],
  steps: ["مسیر استفاده", "How it works", "So funktioniert es", "Nasıl çalışır"],
  unavailable: ["قیمت‌ها اکنون در دسترس نیستند. برای اطلاعات به‌روز با ما تماس بگیرید.", "Prices are currently unavailable. Contact us for current information.", "Preise sind derzeit nicht verfügbar. Kontaktieren Sie uns für aktuelle Informationen.", "Fiyatlar şu anda mevcut değil. Güncel bilgi için bize ulaşın."],
} satisfies Record<string, Copy>;

export type Feature = { slug: string; route: string; title: Copy; desc: Copy; items: readonly Copy[]; requirement: Copy; category: "work" | "create" | "learn" };
export const features: Feature[] = [
  { slug: "startup", route: "/startup/builder", category: "work", title: ["سازندهٔ استارتاپ", "Startup builder", "Startup-Builder", "Girişim oluşturucu"], desc: ["ایدهٔ کسب‌وکار را با راهنمای AI به یک برنامهٔ قابل بررسی تبدیل کنید.", "Turn a business idea into a plan you can review with AI guidance.", "Eine Geschäftsidee mit KI-Unterstützung in einen prüfbaren Plan verwandeln.", "İş fikrinizi yapay zekâ rehberliğiyle inceleyebileceğiniz bir plana dönüştürün."], items: [["توسعهٔ ایده", "Idea development", "Ideenentwicklung", "Fikir geliştirme"], ["برنامهٔ کسب‌وکار", "Business planning", "Geschäftsplanung", "İş planlaması"], ["درخواست مشاوره", "Consultation inquiry", "Beratungsanfrage", "Danışmanlık talebi"]], requirement: ["اعتبار و دسترسی ابزار لازم است. پیشنهادها تضمین موفقیت یا جذب سرمایه نیستند.", "Credits and tool access required. Suggestions do not guarantee success or investment.", "Credits und Tool-Zugriff erforderlich. Keine Erfolgs- oder Investitionsgarantie.", "Kredi ve araç erişimi gerekir. Öneriler başarı veya yatırım garantisi vermez."] },
  { slug: "websites", route: "/website-designer", category: "create", title: ["طراحی وبسایت", "Website designer", "Website-Designer", "Web sitesi tasarımcısı"], desc: ["با کمک AI پیش‌نویس سایت بسازید و طرح و خروجی را بررسی کنید.", "Create a website draft with AI and review the design and output.", "Mit KI einen Website-Entwurf erstellen und Design und Ergebnis prüfen.", "Yapay zekâ ile site taslağı oluşturun ve tasarımı ve çıktıyı inceleyin."], items: [["شرح پروژه", "Project brief", "Projektbeschreibung", "Proje özeti"], ["طرح تولیدشده", "Generated design", "Generiertes Design", "Üretilen tasarım"], ["مدیریت پروژه‌ها", "Project management", "Projektverwaltung", "Proje yönetimi"]], requirement: ["دسترسی کسب‌وکار و اعتبار لازم است؛ دامنه، میزبانی و انتشار به تنظیمات پروژه وابسته‌اند.", "Business access and credits required; domains, hosting and publishing depend on project setup.", "Business-Zugriff und Credits erforderlich; Domain, Hosting und Veröffentlichung hängen vom Projekt ab.", "İşletme erişimi ve kredi gerekir; alan adı, barındırma ve yayın proje kurulumuna bağlıdır."] },
  { slug: "meetings", route: "/meeting", category: "work", title: ["جلسهٔ مشاوران AI", "AI advisory meeting", "KI-Beratungssitzung", "Yapay zekâ danışman toplantısı"], desc: ["یک موضوع بدهید و دیدگاه چند مشاور AI را در یک گفتگوی شبیه‌سازی‌شده بررسی کنید.", "Choose a topic and review several AI advisers' perspectives in a simulated discussion.", "Ein Thema wählen und Perspektiven mehrerer KI-Berater in einer simulierten Diskussion prüfen.", "Bir konu seçin ve simüle edilmiş tartışmada farklı yapay zekâ danışmanlarının görüşlerini inceleyin."], items: [["انتخاب مشاوران", "Select advisers", "Berater auswählen", "Danışman seçimi"], ["گفتگوی شبیه‌سازی‌شده", "Simulated discussion", "Simulierte Diskussion", "Simüle edilmiş tartışma"], ["کپی خروجی", "Copy output", "Ergebnis kopieren", "Çıktıyı kopyalama"]], requirement: ["دسترسی کسب‌وکار و اعتبار لازم است. مشاوران، نقش‌های AI هستند نه اشخاص حقیقی؛ توصیه‌ها را بررسی کنید.", "Business access and credits required. Advisers are AI roles, not real people; review their suggestions.", "Business-Zugriff und Credits erforderlich. Berater sind KI-Rollen, keine echten Personen; Vorschläge prüfen.", "İşletme erişimi ve kredi gerekir. Danışmanlar gerçek kişiler değil, yapay zekâ rolleridir; önerileri inceleyin."] },
  { slug: "assistant", route: "/chat", category: "work", title: ["دستیار هوشمند", "AI assistant", "KI-Assistent", "Yapay zekâ asistanı"], desc: ["فکر کنید، بنویسید و سؤال بپرسید؛ گفتگوها در حساب شما باقی می‌مانند.", "Think, write and ask questions, with conversations saved in your account.", "Denken, schreiben und fragen. Gespräche bleiben in Ihrem Konto gespeichert.", "Düşünün, yazın ve soru sorun. Sohbetler hesabınızda saklanır."], items: [["گفتگو و سابقه", "Chat & history", "Chat & Verlauf", "Sohbet ve geçmiş"], ["انتخاب مدل", "Model selection", "Modellauswahl", "Model seçimi"], ["دستیارهای تخصصی", "Specialist assistants", "Spezialisierte Assistenten", "Uzman asistanlar"]], requirement: ["ورود و اعتبار کافی؛ هزینه به مدل انتخاب‌شده بستگی دارد.", "Sign-in and sufficient credits; cost depends on the selected model.", "Anmeldung und genügend Credits; Kosten abhängig vom Modell.", "Giriş ve yeterli kredi gerekir; maliyet seçilen modele bağlıdır."] },
  { slug: "agents", route: "/agents", category: "work", title: ["تیم و ایجنت‌های AI", "AI agents & team", "KI-Agenten & Team", "Yapay zekâ ajanları ve ekip"], desc: ["از تحلیل کسب‌وکار تا زنجیرهٔ تولید محتوای سئو، در فضای کاری مرتبط.", "From business analysis to an SEO content pipeline, inside connected workspaces.", "Von Unternehmensanalysen bis zur SEO-Content-Pipeline in passenden Arbeitsbereichen.", "İş analizinden SEO içerik akışına, ilgili çalışma alanlarında."], items: [["دکتر کسب‌وکار", "Business doctor", "Business-Diagnose", "İşletme doktoru"], ["هماهنگ‌کنندهٔ کسب‌وکار", "Business orchestrator", "Business-Koordination", "İş koordinatörü"], ["زنجیرهٔ محتوا", "Content pipeline", "Content-Pipeline", "İçerik akışı"]], requirement: ["دسترسی ماژول، اعتبار و برای انتشار، اتصال سایت لازم است؛ خروجی AI باید بررسی شود.", "Module access and credits required; publishing needs a site connection. Review AI output.", "Modulzugriff und Credits erforderlich; Veröffentlichung benötigt eine Website-Verbindung. KI-Ausgaben prüfen.", "Modül erişimi ve kredi gerekir; yayın için site bağlantısı gerekir. Yapay zekâ çıktısını inceleyin."] },
  { slug: "crm", route: "/crm", category: "work", title: ["CRM و فروش", "CRM & sales", "CRM & Vertrieb", "CRM ve satış"], desc: ["مشتری، فرصت فروش، فعالیت و پیگیری را در یک فضای مشخص مدیریت کنید.", "Manage contacts, sales opportunities, activities and follow-ups in one workspace.", "Kontakte, Verkaufschancen, Aktivitäten und Follow-ups gemeinsam verwalten.", "Kişileri, satış fırsatlarını, etkinlikleri ve takipleri tek alanda yönetin."], items: [["مخاطبان و فرصت‌ها", "Contacts & opportunities", "Kontakte & Chancen", "Kişiler ve fırsatlar"], ["وظایف و فعالیت‌ها", "Tasks & activities", "Aufgaben & Aktivitäten", "Görevler ve etkinlikler"], ["اعضا و دسترسی", "Team & access", "Team & Zugriff", "Ekip ve erişim"]], requirement: ["اشتراک CRM فعال و دسترسی کسب‌وکار لازم است؛ ظرفیت تیم به پلن بستگی دارد.", "Active CRM subscription and business access required; team capacity depends on the plan.", "Aktives CRM-Abo und Business-Zugriff erforderlich; Teamgröße abhängig vom Tarif.", "Etkin CRM aboneliği ve işletme erişimi gerekir; ekip kapasitesi plana bağlıdır."] },
  { slug: "leads", route: "/lead-gen", category: "work", title: ["جمع‌آوری لید", "Lead capture", "Lead-Erfassung", "Potansiyel müşteri toplama"], desc: ["فرم‌های جذب لید و اتصال منابع را کنار پیگیری مشتری داشته باشید.", "Bring lead forms and source connections together with customer follow-up.", "Lead-Formulare und Quellen mit der Kundenbetreuung verbinden.", "Formları ve kaynak bağlantılarını müşteri takibiyle birleştirin."], items: [["فرم عمومی", "Public lead forms", "Öffentliche Lead-Formulare", "Herkese açık formlar"], ["اتصال منابع", "Source connectors", "Quellenverbindungen", "Kaynak bağlantıları"], ["گزارش لید", "Lead reports", "Lead-Berichte", "Müşteri raporları"]], requirement: ["دسترسی کسب‌وکار؛ اتصال Meta و Google به تنظیمات و مجوز حساب نیاز دارد. افزایش فروش تضمین نمی‌شود.", "Business access; Meta and Google connectors need configuration and account permissions. No sales guarantee.", "Business-Zugriff; Meta und Google benötigen Konfiguration und Berechtigungen. Keine Umsatzgarantie.", "İşletme erişimi; Meta ve Google bağlantıları yapılandırma ve izin gerektirir. Satış garantisi yoktur."] },
  { slug: "social", route: "/social", category: "work", title: ["شبکه‌های اجتماعی", "Social media", "Social Media", "Sosyal medya"], desc: ["حساب متصل، قوانین پاسخ و محتوای شبکهٔ اجتماعی را در یک داشبورد مدیریت کنید.", "Manage connected accounts, reply rules and social content in one dashboard.", "Verbundene Konten, Antwortregeln und Social Content gemeinsam verwalten.", "Bağlı hesapları, yanıt kurallarını ve sosyal içeriği tek panelde yönetin."], items: [["اتوماسیون کامنت و دایرکت", "Comment-to-DM automation", "Kommentar-zu-DM-Automation", "Yorumdan DM otomasyonu"], ["صندوق پیام", "Inbox", "Posteingang", "Gelen kutusu"], ["محتوا و انتشار", "Content & publishing", "Inhalte & Veröffentlichung", "İçerik ve yayın"]], requirement: ["حساب حرفه‌ای اینستاگرام، اتصال Meta، مجوزها و وبهوک صحیح لازم‌اند. محدودیت‌های Meta اعمال می‌شوند.", "Professional Instagram account, Meta connection, permissions and configured webhooks required. Meta limits apply.", "Professionelles Instagram-Konto, Meta-Verbindung, Berechtigungen und Webhooks erforderlich. Meta-Limits gelten.", "Profesyonel Instagram hesabı, Meta bağlantısı, izinler ve web kancaları gerekir. Meta sınırları geçerlidir."] },
  { slug: "content", route: "/seo/agent-pipeline", category: "create", title: ["محتوا و سئو", "Content & SEO", "KI-Inhalte und SEO", "İçerik ve SEO"], desc: ["پژوهش، پیش‌نویس، ویرایش و بررسی سئو را در یک مسیر ادامه دهید.", "Move from research to drafts, editing and SEO checks in one pipeline.", "Recherche, Entwurf, Bearbeitung und SEO-Prüfung in einer Pipeline.", "Araştırmadan taslağa, düzenlemeye ve SEO kontrolüne tek akışta ilerleyin."], items: [["ممیزی سایت", "Site audits", "Website-Audits", "Site denetimleri"], ["زنجیرهٔ عوامل محتوا", "Content agent pipeline", "Content-Agenten-Pipeline", "İçerik ajan akışı"], ["اتصال وردپرس", "WordPress connection", "WordPress-Verbindung", "WordPress bağlantısı"]], requirement: ["دسترسی SEO، اعتبار و اتصال سایت برای انتشار لازم‌اند؛ رتبهٔ گوگل تضمین نمی‌شود.", "SEO access and credits required, plus a site connection to publish. No Google ranking guarantee.", "SEO-Zugriff, Credits und Website-Verbindung zur Veröffentlichung erforderlich. Keine Ranking-Garantie.", "SEO erişimi ve kredi, yayın için site bağlantısı gerekir. Google sıralaması garanti edilmez."] },
  { slug: "images", route: "/image/generate", category: "create", title: ["تولید تصویر", "Image creation", "Bilderstellung", "Görsel üretimi"], desc: ["ایده را به تصویر تبدیل کنید و خروجی‌ها را در گالری حساب نگه دارید.", "Turn ideas into images and keep your outputs in your account gallery.", "Ideen in Bilder verwandeln und Ergebnisse in Ihrer Galerie speichern.", "Fikirleri görsellere dönüştürün ve çıktıları galerinizde saklayın."], items: [["متن به تصویر", "Text to image", "Text zu Bild", "Metinden görsele"], ["تصویر مرجع", "Reference images", "Referenzbilder", "Referans görseller"], ["گالری خروجی", "Output gallery", "Ergebnisgalerie", "Çıktı galerisi"]], requirement: ["اعتبار، مدل در دسترس و رعایت حقوق محتوا لازم است؛ کیفیت و تعداد بر مصرف اثر دارد.", "Credits, an available model and content rights required; quality and quantity affect usage.", "Credits, verfügbares Modell und Inhaltsrechte erforderlich; Qualität und Anzahl beeinflussen den Verbrauch.", "Kredi, kullanılabilir model ve içerik hakları gerekir; kalite ve adet kullanımı etkiler."] },
  { slug: "video", route: "/video/generate", category: "create", title: ["ویدئو و موسیقی", "Video & music", "Video & Musik", "Video ve müzik"], desc: ["برای پروژهٔ خلاقانهٔ بعدی، ویدئو یا موسیقی بسازید و خروجی را مرور کنید.", "Create video or music for your next creative project and review saved results.", "Videos oder Musik für Ihr nächstes kreatives Projekt erstellen und Ergebnisse prüfen.", "Bir sonraki yaratıcı projeniz için video veya müzik üretin ve sonuçları inceleyin."], items: [["تولید ویدئو", "Video generation", "Videogenerierung", "Video üretimi"], ["تولید موسیقی", "Music generation", "Musikgenerierung", "Müzik üretimi"], ["تاریخچهٔ خروجی‌ها", "Saved outputs", "Gespeicherte Ergebnisse", "Kaydedilen çıktılar"]], requirement: ["اعتبار و ارائه‌دهندهٔ فعال لازم است. زمان تولید و امکانات به مدل و مدت خروجی بستگی دارد.", "Credits and an active provider required. Generation time and options depend on model and duration.", "Credits und aktiver Anbieter erforderlich. Dauer und Optionen hängen vom Modell und der Länge ab.", "Kredi ve etkin sağlayıcı gerekir. Süre ve seçenekler modele ve çıktı uzunluğuna bağlıdır."] },
  { slug: "voice", route: "/voice-agent", category: "work", title: ["دستیار صوتی", "Voice agent", "Sprachagent", "Sesli ajan"], desc: ["تماس‌ها، دستیار صوتی و اطلاعات مرتبط را در فضای کسب‌وکار مرور کنید.", "Review calls, voice assistants and related context in your business workspace.", "Anrufe, Sprachassistenten und Kontext im Business-Bereich prüfen.", "Aramaları, sesli asistanları ve ilgili bilgileri işletme alanında inceleyin."], items: [["پیکربندی دستیار", "Assistant configuration", "Assistent konfigurieren", "Asistan yapılandırması"], ["سوابق تماس", "Call history", "Anrufverlauf", "Arama geçmişi"], ["اطلاعات املاک", "Property context", "Immobilienkontext", "Emlak bilgileri"]], requirement: ["اشتراک و تنظیمات ارائه‌دهندهٔ صوت/تلفن لازم است؛ تماس واقعی صرفاً با وجود اتصال فعال ممکن است.", "Subscription and voice/telephony provider configuration required; live calls need an active connection.", "Abo und Sprach-/Telefonie-Anbieter erforderlich; echte Anrufe benötigen eine aktive Verbindung.", "Abonelik ve ses/telefon sağlayıcısı yapılandırması gerekir; gerçek aramalar etkin bağlantı gerektirir."] },
  { slug: "accounting", route: "/accounting", category: "work", title: ["حسابداری", "Accounting", "Buchhaltung", "Muhasebe"], desc: ["هزینه‌ها، اسناد، بانک و گزارش‌های مالی را در فضای کسب‌وکار دنبال کنید.", "Track expenses, entries, banking and financial reports in your business workspace.", "Ausgaben, Buchungen, Bankdaten und Finanzberichte im Business-Bereich verfolgen.", "Giderleri, kayıtları, banka işlemlerini ve mali raporları işletme alanında takip edin."], items: [["دفتر و هزینه‌ها", "Ledger & expenses", "Buchungen & Ausgaben", "Defter ve giderler"], ["بانک و تطبیق", "Bank & reconciliation", "Bank & Abstimmung", "Banka ve mutabakat"], ["حقوق و گزارش‌ها", "Payroll & reports", "Lohnabrechnung & Berichte", "Bordro ve raporlar"]], requirement: ["دسترسی ماژول مالی و اطلاعات صحیح لازم است؛ خروجی AI جایگزین تأیید حسابدار یا مشاور مالیاتی نیست.", "Finance access and accurate data required; AI output does not replace accountant or tax adviser review.", "Finanzzugriff und korrekte Daten erforderlich; KI ersetzt keine Prüfung durch Buchhaltung oder Steuerberatung.", "Finans erişimi ve doğru veri gerekir; yapay zekâ muhasebeci veya vergi danışmanı incelemesinin yerini almaz."] },
  { slug: "property", route: "/crm", category: "work", title: ["مدیریت املاک", "Real estate workspace", "Immobilien-Arbeitsbereich", "Emlak çalışma alanı"], desc: ["ملک، مشتری، بازدید و قرارداد را در کنار پیگیری فروش مدیریت کنید.", "Manage properties, clients, viewings and contracts alongside sales follow-up.", "Immobilien, Kunden, Besichtigungen und Verträge mit Vertriebs-Follow-ups verwalten.", "Mülkleri, müşterileri, ziyaretleri ve sözleşmeleri satış takibiyle yönetin."], items: [["فایل‌های ملکی", "Property listings", "Immobilienangebote", "Emlak ilanları"], ["بازدید و رزرو", "Viewings & bookings", "Besichtigungen & Buchungen", "Ziyaretler ve rezervasyonlar"], ["قرارداد و کمیسیون", "Contracts & commissions", "Verträge & Provisionen", "Sözleşmeler ve komisyonlar"]], requirement: ["اشتراک CRM و صنعت املاک فعال لازم است؛ قیمت پیشنهادی AI ارزیابی رسمی ملک نیست.", "Active CRM subscription and real-estate industry required; AI price advice is not a certified valuation.", "Aktives CRM-Abo und Immobilienbranche erforderlich; KI-Preisberatung ist kein zertifiziertes Gutachten.", "Etkin CRM aboneliği ve emlak sektörü gerekir; yapay zekâ fiyat önerisi resmi değerleme değildir."] },
  { slug: "education", route: "/student", category: "learn", title: ["فضای دانشجویی", "Student workspace", "Studierendenbereich", "Öğrenci çalışma alanı"], desc: ["درس و جزوه، برنامهٔ امتحان و گزارش مطالعه را در یک فضای منظم داشته باشید.", "Keep courses, materials, exam plans and study reports in one organized workspace.", "Kurse, Unterlagen, Prüfungspläne und Lernberichte übersichtlich zusammenführen.", "Dersleri, notları, sınav planlarını ve çalışma raporlarını düzenli bir alanda tutun."], items: [["درس و جزوه", "Courses & materials", "Kurse & Unterlagen", "Dersler ve materyaller"], ["زمان‌سنج و گزارش", "Study timer & reports", "Lerntimer & Berichte", "Çalışma sayacı ve raporlar"], ["گروه و گفتگوی درسی", "Groups & study chat", "Gruppen & Lernchat", "Gruplar ve ders sohbeti"]], requirement: ["ماژول دانشجویی فعال لازم است. OCR/رونویسی به ارائه‌دهنده و یادآورها به زمان‌بند نیاز دارند؛ کمک AI باید با قواعد دانشگاه سازگار باشد.", "Student module must be enabled. OCR/transcription need providers; reminders need scheduling. Follow your institution's AI policies.", "Studierendenmodul muss aktiv sein. OCR/Transkription benötigen Anbieter, Erinnerungen einen Zeitplaner. KI-Regeln der Hochschule beachten.", "Öğrenci modülü etkin olmalıdır. OCR/transkripsiyon sağlayıcı, hatırlatmalar zamanlayıcı gerektirir. Üniversitenizin yapay zekâ kurallarına uyun."] },
];

// Stable product order: primary assistant, business, creation, learning.
const featureOrder = ["assistant", "agents", "crm", "leads", "social", "content", "images", "video", "voice", "accounting", "property", "education", "startup", "websites", "meetings"];
features.sort((a, b) => featureOrder.indexOf(a.slug) - featureOrder.indexOf(b.slug));

export const solutionCatalog = [
  { slug: "business", title: ["کسب‌وکار و تیم", "Business & teams", "Unternehmen & Teams", "İşletmeler ve ekipler"] as Copy, modules: ["crm", "leads", "accounting", "agents"] },
  { slug: "creators", title: ["تولیدکنندگان محتوا", "Creators & marketers", "Kreative & Marketing", "İçerik üreticileri ve pazarlamacılar"] as Copy, modules: ["content", "images", "video", "social"] },
  { slug: "real-estate", title: ["مشاوران و کسب‌وکارهای املاک", "Real estate businesses", "Immobilienunternehmen", "Emlak işletmeleri"] as Copy, modules: ["property", "crm", "leads", "voice"] },
  { slug: "students", title: ["دانشجویان و یادگیری", "Students & learning", "Studierende & Lernen", "Öğrenciler ve öğrenme"] as Copy, modules: ["education", "assistant"] },
];
