import type { Copy } from "./catalog";
export type Guide = { slug: string; title: Copy; description: Copy; related: string[]; sections: { title: Copy; body: Copy }[] };
export const CONTENT_UPDATED_AT = "2026-10-03";
export const guides: Guide[] = [
  {
    slug: "ai-crm-lead-follow-up",
    title: ["مدیریت و پیگیری مشتری با CRM و هوش مصنوعی", "How to follow up with leads using CRM and AI", "Kunden mit CRM und KI nachverfolgen", "CRM ve yapay zekâ ile müşteri takibi"],
    description: ["از ثبت سرنخ تا پیگیری فروش: روشی عملی برای مرتب‌کردن اطلاعات مشتری، تعیین اقدام بعدی و بررسی پیش‌نویس‌های AI در AIFekr.", "A practical workflow for organizing customer data, choosing the next sales action and reviewing AI follow-up drafts in AIFekr.", "Ein praktischer Ablauf für Kundendaten, nächste Vertriebsschritte und die Prüfung von KI-Follow-up-Entwürfen in AIFekr.", "AIFekr'de müşteri verilerini düzenleme, sonraki satış adımını seçme ve yapay zekâ takip taslaklarını inceleme akışı."],
    related: ["crm", "leads", "voice", "property"],
    sections: [
      { title: ["چه زمانی به CRM نیاز دارید؟", "When does CRM help?", "Wann hilft ein CRM?", "CRM ne zaman yardımcı olur?"], body: ["وقتی اطلاعات مشتری میان پیام‌ها، فایل‌ها و یادداشت‌ها پراکنده است، پیگیری به حافظهٔ افراد وابسته می‌شود. CRM کمک می‌کند هر سرنخ یک مسئول، وضعیت و اقدام بعدی داشته باشد. هدف، افزایش تعداد فیلدها نیست؛ اطلاعاتی را ثبت کنید که برای تصمیم بعدی لازم دارید، مثل نیاز مشتری، روش تماس و زمان پیگیری.", "When customer details are scattered across messages and notes, follow-up depends on memory. A CRM gives each lead an owner, status and next action. Start with the customer's need, contact method and follow-up date rather than filling every possible field.", "Sind Kundendaten über Nachrichten und Notizen verteilt, hängt Nachverfolgung vom Gedächtnis ab. Ein CRM gibt jedem Lead einen Verantwortlichen, Status und nächsten Schritt. Beginnen Sie mit Bedarf, Kontaktweg und Wiedervorlagedatum statt mit allen möglichen Feldern.", "Müşteri bilgileri mesaj ve notlara dağıldığında takip hafızaya bağlı kalır. CRM her adaya sorumlu, durum ve sonraki adım verir. Her alanı doldurmak yerine ihtiyaç, iletişim yöntemi ve takip tarihiyle başlayın."] },
      { title: ["از فرم جذب مشتری تا پیگیری", "From a lead form to follow-up", "Vom Lead-Formular zur Nachverfolgung", "Aday müşteri formundan takibe"], body: ["در بخش تولید لید، فرم متناسب با هدف بسازید و فقط اطلاعات لازم را بخواهید. منبع سرنخ را نگه دارید تا بدانید کدام کانال مشتری مرتبط می‌آورد. سپس در CRM مشتری و معامله را بررسی کنید و یک تسک با موعد مشخص بسازید. اتصال خودکار کانال‌هایی مانند Meta به مجوز و اتصال فعال نیاز دارد؛ ساخت فرم به‌تنهایی این اتصال را برقرار نمی‌کند.", "Build a lead form around a specific goal and request only necessary details. Keep the source to compare channels. Review the customer and deal in CRM, then create a dated follow-up task. Automatic channel imports, including Meta, require an active connection and permissions.", "Erstellen Sie ein zielgerichtetes Formular und fragen Sie nur nötige Daten ab. Speichern Sie die Quelle zum Kanalvergleich. Prüfen Sie Kunde und Geschäft im CRM und erstellen Sie eine Aufgabe mit Termin. Automatische Importe wie Meta benötigen aktive Verbindungen und Berechtigungen.", "Belirli bir hedef için form oluşturup yalnızca gerekli bilgileri isteyin. Kanalları karşılaştırmak için kaynağı saklayın. CRM'de müşteri ve fırsatı inceleyip tarihli takip görevi oluşturun. Meta gibi otomatik kanal aktarımları etkin bağlantı ve izin gerektirir."] },
      { title: ["AI پیش‌نویس می‌سازد؛ شما تأیید می‌کنید", "AI drafts; you review", "KI entwirft, Sie prüfen", "Yapay zekâ taslak üretir, siz incelersiniz"], body: ["ایجنت فروش با داده‌های CRM تحلیل و پیام پیگیری پیشنهاد می‌دهد. برای مثال، اگر مشتری منتظر قیمت یا زمان بازدید است، متن باید دقیقاً همین اقدام را روشن کند. نام، قیمت، وعده و اطلاعات تماس را با دادهٔ واقعی تطبیق دهید. ارسال ایمیل یک اقدام جداگانه است و اتصال ایمیل لازم دارد؛ تولید پیش‌نویس را با ارسال موفق اشتباه نگیرید.", "The Sales Agent uses CRM context to suggest analysis and follow-up messages. If a customer awaits pricing or a viewing, the draft should address that next step. Verify names, prices, commitments and contact details. Email sending is a separate action that requires a working email connection.", "Der Vertriebs-Agent nutzt CRM-Kontext für Analysen und Follow-up-Vorschläge. Wartet ein Kunde auf Preis oder Besichtigung, muss der Entwurf genau diesen Schritt klären. Prüfen Sie Namen, Preise, Zusagen und Kontaktdaten. E-Mail-Versand ist eine separate Aktion mit eigener Verbindung.", "Satış ajanı CRM bağlamıyla analiz ve takip mesajı önerir. Müşteri fiyat veya ziyaret bekliyorsa taslak bu adımı açıklamalıdır. İsim, fiyat, taahhüt ve iletişim bilgilerini doğrulayın. E-posta gönderimi çalışan bağlantı gerektiren ayrı bir işlemdir."] },
      { title: ["چه چیزی را اندازه بگیرید؟", "What should you measure?", "Was sollten Sie messen?", "Neyi ölçmelisiniz?"], body: ["تعداد سرنخ به‌تنهایی کافی نیست. زمان اولین پاسخ، تسک‌های عقب‌افتاده و حرکت معاملات میان مراحل را نیز بررسی کنید. از یک فرایند کوچک شروع کنید و دادهٔ ناقص یا تکراری را اصلاح کنید. دسترسی CRM و اعتبار ابزارهای AI قواعد جداگانه دارند؛ قبل از استفادهٔ تیمی، ظرفیت و دسترسی بسته را در صفحهٔ قیمت‌گذاری بررسی کنید.", "Lead count alone is not enough. Review first-response time, overdue tasks and deal movement between stages. Start small and correct duplicate or missing data. CRM access and AI credits follow separate rules; check seats and permissions on the pricing page before team use.", "Die Lead-Anzahl allein reicht nicht. Prüfen Sie Antwortzeit, überfällige Aufgaben und Fortschritt der Geschäfte. Beginnen Sie klein und bereinigen Sie fehlende oder doppelte Daten. CRM-Zugriff und KI-Credits haben getrennte Regeln; prüfen Sie Kapazität und Berechtigungen vor Teamnutzung.", "Aday sayısı tek başına yeterli değildir. İlk yanıt süresini, gecikmiş görevleri ve fırsat aşamalarını inceleyin. Küçük başlayıp eksik veya yinelenen verileri düzeltin. CRM erişimi ve yapay zekâ kredileri farklı kurallara sahiptir; ekip kullanımından önce kapasiteyi kontrol edin."] },
    ],
  },
  {
    slug: "ai-content-seo-workflow",
    title: ["راهنمای تولید محتوای سئو با هوش مصنوعی", "An AI-assisted content and SEO workflow", "Ein Inhalts- und SEO-Ablauf mit KI", "Yapay zekâ destekli içerik ve SEO akışı"],
    description: ["از سؤال مخاطب و ممیزی سایت تا پیش‌نویس، بازبینی و انتشار؛ یک فرایند قابل بررسی برای محتوای مفید و سئوی فنی در AIFekr.", "Move from audience questions and a site audit to drafting, review and publishing with a practical AI-assisted workflow.", "Von Zielgruppenfragen und Website-Prüfung zu Entwurf, Überarbeitung und Veröffentlichung mit einem praktischen KI-Ablauf.", "Hedef kitle sorularından site denetimine, taslağa, incelemeye ve yayına uzanan uygulanabilir yapay zekâ akışı."],
    related: ["content", "social", "websites", "images"],
    sections: [
      { title: ["با سؤال واقعی مخاطب شروع کنید", "Start with a real audience question", "Mit einer echten Zielgruppenfrage beginnen", "Gerçek bir hedef kitle sorusuyla başlayın"], body: ["موضوع محتوا را از نیاز مشتری انتخاب کنید، نه فقط از یک کلمهٔ پرجستجو. مثلاً صفحه‌ای دربارهٔ CRM باید توضیح دهد ثبت مشتری و پیگیری معامله چگونه انجام می‌شود، چه اطلاعاتی لازم است و کدام قابلیت‌ها به اشتراک نیاز دارند. هدف جستجو، عنوان و پاسخ اصلی صفحه را پیش از نوشتن مشخص کنید تا چند صفحه با یک پاسخ تکراری نسازید.", "Choose a topic from customer needs rather than keyword volume alone. A CRM page should explain customer records, deal follow-up, required information and access rules. Define the search intent, title and main answer before drafting so multiple pages do not repeat the same answer.", "Wählen Sie Themen aus Kundenbedürfnissen statt nur aus Suchvolumen. Eine CRM-Seite sollte Kundendaten, Nachverfolgung und Zugriff erklären. Definieren Sie Suchintention, Titel und Hauptantwort vor dem Schreiben, damit mehrere Seiten nicht dieselbe Antwort wiederholen.", "Konuyu yalnızca arama hacmine göre değil müşteri ihtiyacına göre seçin. CRM sayfası kayıtları, takibi, gerekli verileri ve erişimi açıklamalıdır. Birden fazla sayfanın aynı yanıtı tekrarlamaması için önce arama amacını, başlığı ve temel yanıtı belirleyin."] },
      { title: ["محتوا و سلامت فنی را با هم بررسی کنید", "Review content and technical health together", "Inhalte und Technik gemeinsam prüfen", "İçeriği ve teknik sağlığı birlikte inceleyin"], body: ["در فضای کار سئو، نشانی سایت را برای بررسی وارد کنید و یافته‌ها را اولویت‌بندی کنید. عنوان و توضیح هر صفحه، لینک‌های داخلی و ساختار محتوا باید با هدف آن هماهنگ باشند. دسترسی ربات، آدرس اصلی صفحه و نقشهٔ سایت مسائل جداگانهٔ فنی‌اند. نتیجهٔ یک ممیزی، جایگزین مشاهدهٔ وضعیت واقعی ایندکس در Search Console نیست.", "Use the SEO workspace to inspect a site and prioritize findings. Match each page's title, description, internal links and content to its purpose. Crawling, canonical URLs and sitemaps are separate technical concerns. An audit does not replace checking actual indexing in Search Console.", "Prüfen Sie eine Website im SEO-Bereich und priorisieren Sie Ergebnisse. Titel, Beschreibung, interne Links und Inhalt müssen zum Zweck passen. Crawling, Canonical-URLs und Sitemap sind technische Aufgaben. Ein Audit ersetzt nicht die Prüfung der tatsächlichen Indexierung in Search Console.", "SEO alanında siteyi inceleyip bulguları önceliklendirin. Başlık, açıklama, iç bağlantı ve içerik sayfanın amacına uymalıdır. Tarama, canonical adres ve site haritası ayrı teknik konulardır. Denetim, Search Console'daki gerçek indeks durumunun kontrolü yerine geçmez."] },
      { title: ["پیش‌نویس را با اطلاعات قابل تأیید کامل کنید", "Complete drafts with verifiable information", "Entwürfe mit überprüfbaren Angaben ergänzen", "Taslakları doğrulanabilir bilgilerle tamamlayın"], body: ["گردش کار محتوا برای پژوهش، نوشتن و بازبینی کمک می‌کند؛ اما پیش‌نویس AI را بدون بررسی منتشر نکنید. مثال واقعی محصول، مراحل استفاده و محدودیت‌ها را اضافه کنید. قیمت، آمار، منبع و وعدهٔ نتیجه را بررسی کنید و ادعاهای بدون پشتوانه را حذف کنید. متن روشن و مفید از تکرار اجباری کلمات کلیدی ارزشمندتر است.", "The content pipeline helps with research, writing and review, but AI drafts need editorial checks. Add real product examples, steps and limitations. Verify prices, statistics, sources and outcome claims, and remove unsupported statements. Clear, useful writing matters more than repeating keywords.", "Die Pipeline unterstützt Recherche, Schreiben und Prüfung, doch KI-Entwürfe benötigen Redaktion. Ergänzen Sie echte Produktbeispiele, Schritte und Grenzen. Prüfen Sie Preise, Zahlen, Quellen und Versprechen. Verständliche, nützliche Texte sind wichtiger als erzwungene Keyword-Wiederholung.", "İçerik akışı araştırma, yazma ve incelemeyi destekler ancak taslak editör kontrolü gerektirir. Gerçek ürün örnekleri, adımlar ve sınırlamalar ekleyin. Fiyatları, sayıları, kaynakları ve vaatleri doğrulayın. Açık ve faydalı anlatım anahtar kelime tekrarından önemlidir."] },
      { title: ["انتشار و به‌روزرسانی را دنبال کنید", "Track publication and updates", "Veröffentlichung und Aktualisierung verfolgen", "Yayını ve güncellemeleri takip edin"], body: ["انتشار در وردپرس به اتصال معتبر و دسترسی سایت نیاز دارد. پیش از انتشار، پیش‌نمایش، لینک‌ها و منابع را بررسی کنید. بعد از انتشار، کلیک و نمایش واقعی را در Search Console دنبال کنید و محتوای تغییرکرده را به‌روز نگه دارید. ابزار AI یا دادهٔ ساختاریافته رتبهٔ مشخصی را تضمین نمی‌کند؛ کیفیت، دسترسی فنی و ارتباط محتوا با نیاز مخاطب باید کنار هم بهتر شوند.", "WordPress publishing requires a valid site connection. Review the preview, links and sources before publishing. Afterwards, track real impressions and clicks in Search Console and update changed information. AI tools and structured data do not guarantee a ranking; improve usefulness and technical access together.", "WordPress-Veröffentlichung benötigt eine gültige Verbindung. Prüfen Sie Vorschau, Links und Quellen. Verfolgen Sie danach Impressionen und Klicks in Search Console und aktualisieren Sie Änderungen. KI und strukturierte Daten garantieren kein Ranking; verbessern Sie Nutzen und technische Zugänglichkeit gemeinsam.", "WordPress yayını geçerli site bağlantısı gerektirir. Önizlemeyi, bağlantıları ve kaynakları inceleyin. Yayından sonra Search Console'da gösterim ve tıklamaları izleyip değişen bilgileri güncelleyin. Yapay zekâ veya yapılandırılmış veri sıralama garantilemez; faydayı ve teknik erişimi birlikte geliştirin."] },
    ],
  },
  {
    slug: "ai-student-study-planning",
    title: ["برنامه‌ریزی مطالعه و آمادگی امتحان با هوش مصنوعی", "Study planning and exam preparation with AI", "Lernplanung und Prüfungsvorbereitung mit KI", "Yapay zekâ ile çalışma planı ve sınav hazırlığı"],
    description: ["درس، جزوه، امتحان و زمان مطالعه را منظم کنید و از گفتگوی درسی، فلش‌کارت و آزمون AI با بازبینی منابع استفاده کنید.", "Organize courses, materials, exams and study time, then use AI course chat, flashcards and quizzes while checking source material.", "Kurse, Unterlagen, Prüfungen und Lernzeit organisieren und KI-Lernchat, Karten und Quiz mit Quellenprüfung nutzen.", "Ders, materyal, sınav ve çalışma süresini düzenleyip kaynakları kontrol ederek yapay zekâ sohbeti, kartları ve testleri kullanın."],
    related: ["education", "assistant"],
    sections: [
      { title: ["درس‌ها را قبل از تولید محتوا مرتب کنید", "Organize courses before generating content", "Kurse vor der Inhaltserstellung ordnen", "İçerik üretmeden önce dersleri düzenleyin"], body: ["برای هر درس یک فضای مشخص بسازید و منابع و یادداشت‌های همان درس را کنار هم نگه دارید. نام و توضیح واضح کمک می‌کند هنگام پرسیدن سؤال، زمینهٔ درست را انتخاب کنید. ابتدا یک درس و یک منبع کوتاه اضافه کنید؛ سپس بررسی کنید فایل درست وارد شده و متن استخراج‌شده با منبع تطبیق دارد. OCR و رونویسی ممکن است خطا داشته باشند و اعتبار مصرف کنند.", "Give each course its own workspace and keep its materials and notes together. Start with one course and one short source. Check imported files and extracted text before asking questions. OCR and transcription can make errors and may use credits.", "Geben Sie jedem Kurs einen eigenen Bereich und bündeln Sie Unterlagen und Notizen. Beginnen Sie mit einem Kurs und einer kurzen Quelle. Prüfen Sie Import und extrahierten Text vor Fragen. OCR und Transkription können Fehler machen und Credits verbrauchen.", "Her derse ayrı alan verip materyal ve notları bir arada tutun. Bir ders ve kısa kaynakla başlayın. Soru sormadan önce dosyayı ve çıkarılan metni kontrol edin. OCR ve transkripsiyon hata yapabilir ve kredi kullanabilir."] },
      { title: ["از تاریخ امتحان به برنامهٔ قابل اجرا برسید", "Turn exam dates into an actionable plan", "Prüfungstermine in einen machbaren Plan umsetzen", "Sınav tarihini uygulanabilir plana dönüştürün"], body: ["تاریخ امتحان را ثبت کنید و در بخش برنامه و امتحان‌ها، زمان باقی‌مانده را ببینید. تکلیف‌ها را کوچک و مشخص بنویسید؛ مثلاً مرور یک فصل و حل چند سؤال، نه «خواندن کل درس». برنامهٔ پیشنهادی را با زمان واقعی خود تنظیم کنید و برای مرور و استراحت جا بگذارید. برنامهٔ AI یک نقطهٔ شروع است و تضمین نتیجهٔ امتحان نیست.", "Record the exam date and review the time remaining in the planner. Use specific tasks such as one chapter and a few questions instead of an entire course. Adjust suggestions to your available time and leave room for review and rest. An AI plan is a starting point, not a grade guarantee.", "Prüfungstermin eintragen und verbleibende Zeit im Planer prüfen. Formulieren Sie konkrete Aufgaben wie ein Kapitel und einige Fragen. Passen Sie Vorschläge an Ihre Zeit an und planen Sie Wiederholung und Pausen. Ein KI-Plan ist ein Ausgangspunkt, keine Notengarantie.", "Sınav tarihini kaydedip planlayıcıda kalan süreyi inceleyin. Tüm dersi bitirmek yerine bir bölüm ve birkaç soru gibi somut görevler belirleyin. Öneriyi zamanınıza uyarlayıp tekrar ve dinlenmeye yer bırakın. Yapay zekâ planı başlangıçtır, not garantisi değildir."] },
      { title: ["یادگیری فعال را جایگزین خواندن منفعل کنید", "Practice active recall", "Aktives Erinnern üben", "Aktif hatırlama uygulayın"], body: ["بعد از مطالعه، با گفتگوی درسی یک مفهوم را توضیح دهید و از فلش‌کارت یا آزمون برای سنجش فهم خود استفاده کنید. پاسخ را پیش از دیدن جواب بیان کنید و موارد دشوار را دوباره مرور کنید. هر پاسخ تولیدشده را با جزوه یا منبع معتبر تطبیق دهید. برای پایان‌نامه و تکلیف، از AI برای ساختار و بازخورد کمک بگیرید و قواعد دانشگاه دربارهٔ ارجاع و استفاده از AI را رعایت کنید.", "After studying, explain a concept in course chat and use flashcards or a quiz to check understanding. Answer before revealing the solution, then revisit difficult items. Verify generated answers against your course material. For assignments and theses, follow institutional rules on citation and AI use.", "Erklären Sie nach dem Lernen ein Konzept im Kurschat und prüfen Sie Ihr Verständnis mit Karten oder Quiz. Antworten Sie vor Anzeige der Lösung und wiederholen Sie schwierige Punkte. Prüfen Sie KI-Antworten anhand der Unterlagen. Beachten Sie Hochschulregeln zu Zitaten und KI-Nutzung.", "Çalıştıktan sonra kavramı ders sohbetinde açıklayıp kart veya testle anlayışınızı kontrol edin. Yanıtı görmeden cevaplayıp zor konuları tekrar edin. Üretilen yanıtları kaynakla doğrulayın. Ödev ve tezlerde kurumun atıf ve yapay zekâ kurallarına uyun."] },
      { title: ["زمان و پیشرفت را ثبت کنید", "Track time and progress", "Zeit und Fortschritt erfassen", "Süreyi ve ilerlemeyi kaydedin"], body: ["زمان‌سنج و گزارش مطالعه کمک می‌کند ببینید برای کدام درس واقعاً وقت گذاشته‌اید. توقف‌ها و جلسات مطالعه را ثبت کنید و برنامهٔ هفتهٔ بعد را با دادهٔ واقعی تنظیم کنید. در گروه مطالعه، تقسیم کار و یادآوری‌ها باید روشن باشند. دسترسی فضای دانشجویی با اعتبار مصرف ابزارهای AI فرق دارد؛ مدت اشتراک و اعتبار بسته را قبل از خرید جداگانه بررسی کنید.", "Study timers and reports show where your time went. Record pauses and sessions, then adapt next week's plan using real activity. Make responsibilities clear in study groups. Student workspace access differs from AI usage credits; review both subscription duration and package credits before purchasing.", "Lerntimer und Berichte zeigen die tatsächliche Zeitverteilung. Erfassen Sie Pausen und Sitzungen und passen Sie den nächsten Wochenplan an. Klären Sie Zuständigkeiten in Gruppen. Studierendenzugriff und KI-Credits sind getrennt; prüfen Sie Laufzeit und Credits vor dem Kauf.", "Çalışma sayacı ve raporlar zamanın nereye gittiğini gösterir. Mola ve oturumları kaydedip gelecek haftayı gerçek etkinliğe göre düzenleyin. Gruplarda sorumlulukları açıklayın. Öğrenci alanı erişimi yapay zekâ kredilerinden farklıdır; satın almadan önce süre ve kredileri ayrı inceleyin."] },
    ],
  },
];
