import type { Copy } from "./catalog";

type SolutionDetails = { description: Copy; steps: { title: Copy; body: Copy }[]; guide: string };
export const solutionDetails: Record<string, SolutionDetails> = {
  business: {
    description: ["تیم هوش مصنوعی برای کسب‌وکار: CRM، پیگیری مشتری، لید و حسابداری در یک اشتراک، با اعتبار مشترک و ظرفیت مشخص برای اعضای تیم.", "An AI team for your business: CRM, lead capture, customer follow-up and accounting in one subscription, with shared credits and clear team limits.", "Ein KI-Team für Ihr Unternehmen: CRM, Lead-Erfassung, Kundenbetreuung und Buchhaltung in einem Abo mit gemeinsamen Credits und klaren Teamgrenzen.", "İşletmeniz için yapay zekâ ekibi: tek abonelikte CRM, müşteri toplama, takip ve muhasebe; ortak kredi ve belirli ekip kapasitesi."],
    guide: "ai-crm-lead-follow-up",
    steps: [
      { title: ["مشتری و فرصت را ثبت کنید", "Capture contacts and opportunities", "Kontakte und Chancen erfassen", "Kişileri ve fırsatları kaydedin"], body: ["اطلاعات مشتری و وضعیت فرصت فروش را در CRM نگه دارید؛ مسئول پیگیری و اقدام بعدی هر فرصت را مشخص کنید.", "Keep customer details and opportunity stages in CRM. Assign a follow-up owner and the next action for each opportunity.", "Kundendaten und Verkaufsphasen im CRM festhalten. Zuständigkeit und nächste Schritte für jede Chance bestimmen.", "Müşteri bilgilerini ve satış aşamalarını CRM'de tutun. Her fırsat için sorumlu kişiyi ve sonraki adımı belirleyin."] },
      { title: ["پیش‌نویس پیگیری را آماده کنید", "Prepare a follow-up draft", "Follow-up vorbereiten", "Takip taslağı hazırlayın"], body: ["از دستیار برای پیش‌نویس پیام یا تحلیل کسب‌وکار کمک بگیرید. اطلاعات، لحن و مقصد پیام را پیش از ارسال بررسی کنید.", "Use the assistant to draft a message or review a business problem. Check facts, tone and recipient before sending.", "Mit dem Assistenten eine Nachricht entwerfen oder ein Geschäftsproblem prüfen. Fakten, Ton und Empfänger vor dem Versand kontrollieren.", "Asistandan mesaj taslağı veya iş analizi için yardım alın. Göndermeden önce bilgileri, tonu ve alıcıyı kontrol edin."] },
      { title: ["کار تیم را با ظرفیت پلن هماهنگ کنید", "Match the plan to your team's workload", "Tarif an die Teamarbeit anpassen", "Paketi ekibinizin iş yüküne göre seçin"], body: ["همهٔ پکیج‌های بیزنس ابزارهای یکسان دارند؛ تعداد اعضا و اعتبار AI تفاوت دارند. اطلاعات مالی را قبل از استفادهٔ رسمی بررسی کنید.", "Business bundles have the same tools; member capacity and AI credits differ. Review financial records before official use.", "Business-Pakete enthalten dieselben Tools; Mitgliederzahl und KI-Credits unterscheiden sich. Finanzdaten vor offizieller Verwendung prüfen.", "İşletme paketleri aynı araçları sunar; üye kapasitesi ve yapay zekâ kredileri farklıdır. Mali kayıtları resmi kullanımdan önce inceleyin."] },
    ],
  },
  creators: {
    description: ["تولید محتوای هوش مصنوعی برای بازاریابی: از پژوهش و پیش‌نویس مقاله تا تصویر، ویدئو و شبکه‌های اجتماعی، با بررسی انسانی پیش از انتشار.", "AI content creation for marketing: research and article drafts alongside image, video and social tools, with human review before publishing.", "KI-Inhalte für Ihr Marketing: Recherche und Artikelentwürfe zusammen mit Bild-, Video- und Social-Media-Tools, mit Prüfung vor der Veröffentlichung.", "Pazarlama için yapay zekâ içerik üretimi: araştırma ve yazı taslaklarından görsel, video ve sosyal araçlara; yayın öncesinde insan kontrolü."],
    guide: "ai-content-seo-workflow",
    steps: [
      { title: ["موضوع و مخاطب را روشن کنید", "Define the topic and audience", "Thema und Zielgruppe festlegen", "Konuyu ve hedef kitleyi belirleyin"], body: ["نیاز مخاطب، هدف صفحه و اطلاعات معتبر محصول را مشخص کنید. برای هر مقاله یک سؤال اصلی و طرح محتوا آماده کنید.", "Define the audience's need, page goal and verified product facts. Give each article one main question and a content outline.", "Bedarf der Zielgruppe, Seitenziel und belegte Produktinformationen festlegen. Für jeden Artikel eine Kernfrage und Gliederung vorbereiten.", "Hedef kitlenin ihtiyacını, sayfanın amacını ve doğrulanmış ürün bilgilerini belirleyin. Her yazı için ana soru ve içerik planı hazırlayın."] },
      { title: ["متن و رسانه را بسازید", "Create the draft and media", "Text und Medien erstellen", "Metni ve medyayı oluşturun"], body: ["پیش‌نویس را در فضای محتوا آماده کنید و برای تصویر یا ویدئو از ابزار مرتبط استفاده کنید. مصرف اعتبار به مدل و عملیات بستگی دارد.", "Prepare a draft in the content workspace and use the relevant image or video tool. Credit usage depends on the model and action.", "Entwurf im Inhaltsbereich vorbereiten und passende Bild- oder Videowerkzeuge nutzen. Credit-Verbrauch hängt von Modell und Aktion ab.", "İçerik alanında taslak hazırlayın ve ilgili görsel veya video aracını kullanın. Kredi tüketimi modele ve işleme bağlıdır."] },
      { title: ["قبل از انتشار کنترل کنید", "Review before publishing", "Vor der Veröffentlichung prüfen", "Yayından önce kontrol edin"], body: ["صحت ادعاها، عنوان، لینک‌ها و تناسب با مخاطب را بررسی کنید. انتشار در وردپرس یا شبکهٔ اجتماعی به اتصال فعال و مجوز حساب نیاز دارد.", "Check claims, title, links and audience fit. Publishing to WordPress or a social account requires an active connection and permissions.", "Aussagen, Titel, Links und Zielgruppenbezug prüfen. WordPress- oder Social-Veröffentlichung benötigt eine aktive Verbindung und Berechtigungen.", "İddiaları, başlığı, bağlantıları ve kitleye uygunluğu inceleyin. WordPress veya sosyal hesapta yayın için etkin bağlantı ve izin gerekir."] },
    ],
  },
  "real-estate": {
    description: ["هوش مصنوعی برای مشاور املاک: مدیریت فایل ملکی، مشتری، بازدید و پیگیری فروش در CRM، با ابزارهای صوتی وابسته به اتصال ارائه‌دهنده.", "AI for real estate teams: property listings, clients, viewings and sales follow-up in CRM, with voice tools requiring provider connections.", "KI für Immobilienunternehmen: Angebote, Kunden, Besichtigungen und Vertriebs-Follow-ups im CRM; Sprachtools benötigen Anbieter-Verbindungen.", "Emlak ekipleri için yapay zekâ: CRM'de ilan, müşteri, ziyaret ve satış takibi; ses araçları sağlayıcı bağlantısı gerektirir."],
    guide: "ai-crm-lead-follow-up",
    steps: [
      { title: ["فایل و نیاز مشتری را کنار هم ببینید", "Bring listings and client needs together", "Angebote und Kundenbedarf verbinden", "İlanları ve müşteri ihtiyaçlarını birleştirin"], body: ["مشخصات ملک و اطلاعات مشتری را ثبت کنید. قیمت، وضعیت فایل و نیاز مشتری را با اطلاعات تأییدشده به‌روز نگه دارید.", "Record property details and client information. Keep prices, listing status and client requirements current using verified facts.", "Immobiliendetails und Kundendaten erfassen. Preise, Angebotsstatus und Anforderungen mit bestätigten Informationen aktuell halten.", "Mülk ve müşteri bilgilerini kaydedin. Fiyatı, ilan durumunu ve müşteri ihtiyaçlarını doğrulanmış bilgilerle güncel tutun."] },
      { title: ["بازدید و پیگیری را برنامه‌ریزی کنید", "Plan viewings and follow-up", "Besichtigungen und Follow-ups planen", "Ziyaretleri ve takipleri planlayın"], body: ["برای فرصت فروش، بازدید و اقدام بعدی ثبت کنید. از پیش‌نویس AI برای پیام پیگیری کمک بگیرید و زمان و جزئیات را خودتان تأیید کنید.", "Record viewings and next actions against the sales opportunity. Use AI to draft follow-up messages and verify dates and details yourself.", "Besichtigungen und nächste Schritte bei der Verkaufschance erfassen. KI für Nachrichtenentwürfe nutzen und Termine sowie Details selbst bestätigen.", "Satış fırsatı için ziyaretleri ve sonraki adımları kaydedin. Takip mesajı taslağında yapay zekâ kullanın, tarihleri ve ayrıntıları doğrulayın."] },
      { title: ["اتصال و اسناد را بررسی کنید", "Check connections and documents", "Verbindungen und Unterlagen prüfen", "Bağlantıları ve belgeleri kontrol edin"], body: ["تماس واقعی به سرویس تلفن متصل نیاز دارد. قرارداد، کمیسیون و پیشنهاد قیمت AI را پیش از تصمیم یا امضا با متخصص مربوط بررسی کنید.", "Live calls require a connected telephony service. Review contracts, commissions and AI price suggestions with the appropriate professional before deciding or signing.", "Echte Anrufe benötigen einen verbundenen Telefoniedienst. Verträge, Provisionen und KI-Preisvorschläge vor Entscheidungen oder Unterschriften fachlich prüfen lassen.", "Gerçek aramalar bağlı telefon hizmeti gerektirir. Karar veya imza öncesinde sözleşme, komisyon ve yapay zekâ fiyat önerilerini uzmanla inceleyin."] },
    ],
  },
  students: {
    description: ["دستیار هوش مصنوعی دانشجویی برای درس، جزوه، فلش‌کارت و آزمون تمرینی؛ برنامهٔ مطالعه، امتحان‌ها و گزارش پیشرفت در یک فضای شخصی.", "An AI student assistant for courses, notes, flashcards and practice quizzes, with study planning, exams and progress reports in one personal workspace.", "KI-Lernassistent für Kurse, Unterlagen, Lernkarten und Übungstests mit Lernplanung, Prüfungen und Fortschrittsberichten in einem persönlichen Bereich.", "Ders, not, bilgi kartı ve deneme sınavları için yapay zekâ öğrenci asistanı; kişisel alanda çalışma planı, sınavlar ve ilerleme raporları."],
    guide: "ai-student-study-planning",
    steps: [
      { title: ["درس و منابع خودتان را اضافه کنید", "Add your courses and source materials", "Kurse und eigene Unterlagen hinzufügen", "Derslerinizi ve kaynaklarınızı ekleyin"], body: ["درس را بسازید و جزوه یا متن کلاس را به آن اضافه کنید. برای پاسخ‌های قابل بررسی، منابع کامل و خوانا وارد کنید.", "Create a course and add your notes or lecture text. Use complete, readable sources so you can check the tutor's answers.", "Kurs anlegen und Unterlagen oder Vorlesungstexte hinzufügen. Vollständige, lesbare Quellen erleichtern die Prüfung der Antworten.", "Ders oluşturun ve notlarınızı veya ders metnini ekleyin. Asistan yanıtlarını kontrol etmek için eksiksiz ve okunaklı kaynaklar kullanın."] },
      { title: ["مطالعه را به تمرین تبدیل کنید", "Turn studying into practice", "Lernen durch Übung vertiefen", "Çalışmayı pratiğe dönüştürün"], body: ["از جزوه سؤال بپرسید، فلش‌کارت بسازید یا آزمون تمرینی بگیرید. پاسخ و توضیح AI را با منبع و نظر استاد مقایسه کنید.", "Ask questions about your materials, make flashcards or take a practice quiz. Compare AI explanations with your source and instructor guidance.", "Fragen zu Unterlagen stellen, Lernkarten erstellen oder Übungstests nutzen. KI-Erklärungen mit Quellen und Lehrhinweisen vergleichen.", "Kaynaklarınız hakkında soru sorun, bilgi kartı oluşturun veya deneme sınavı çözün. Yapay zekâ açıklamalarını kaynak ve eğitmen bilgisiyle karşılaştırın."] },
      { title: ["برنامه و زمان مطالعه را دنبال کنید", "Track your study plan and time", "Lernplan und Lernzeit verfolgen", "Çalışma planını ve süreyi takip edin"], body: ["امتحان‌ها و وظایف را ثبت کنید و زمان‌سنج مطالعه را به کار بگیرید. از گزارش‌ها برای تنظیم برنامه استفاده کنید و قواعد دانشگاه دربارهٔ AI را رعایت کنید.", "Record exams and tasks, and use the study timer. Adjust your plan using study reports and follow your institution's rules on AI use.", "Prüfungen und Aufgaben erfassen und den Lerntimer nutzen. Planung anhand der Berichte anpassen und KI-Regeln der Hochschule beachten.", "Sınav ve görevleri kaydedin, çalışma sayacını kullanın. Raporlarla planınızı düzenleyin ve üniversitenizin yapay zekâ kurallarına uyun."] },
    ],
  },
};
