import {NextRequest,NextResponse} from "next/server";
import {requireAdmin,forbiddenResponse} from "@/lib/auth/middleware";
import {prisma} from "@/lib/db/prisma";
import {z} from "zod";
export const dynamic="force-dynamic";
/** Reissue the same authoritative PDF; never reactivate a revoked certificate. */
export async function POST(req:NextRequest){const admin=await requireAdmin(req);if(!admin)return forbiddenResponse();const input=z.object({id:z.string(),reason:z.string().trim().min(10).max(2000),confirm:z.literal(true)}).strict().safeParse(await req.json().catch(()=>null));if(!input.success)return NextResponse.json({error:"REISSUE_REASON_REQUIRED"},{status:400});const c=await prisma.aiCourseCertificate.findUnique({where:{id:input.data.id},include:{completion:true}});if(!c)return NextResponse.json({error:"NOT_FOUND"},{status:404});if(c.status!=="ACTIVE")return NextResponse.json({error:"CERTIFICATE_REVOKED"},{status:410});await prisma.auditLog.create({data:{actorId:admin.id,action:"academy_certificate_reissued",targetId:c.id,metadata:JSON.stringify({reason:input.data.reason,completionId:c.completionId,preservesIdentity:true})}});return NextResponse.json({downloadUrl:`/api/learn/courses/${c.completion.courseId}/certificate?certificate=${c.id}`});}
export async function GET(req:NextRequest){if(!await requireAdmin(req))return forbiddenResponse();const search=req.nextUrl.searchParams.get("search")?.slice(0,200)||"",status=req.nextUrl.searchParams.get("status"),userId=req.nextUrl.searchParams.get("userId"),courseId=req.nextUrl.searchParams.get("courseId");const from=req.nextUrl.searchParams.get("from"),to=req.nextUrl.searchParams.get("to");if([from,to].some(d=>d&&(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d)))))return NextResponse.json({error:"INVALID_DATE_FILTER"},{status:400});const certificates=await prisma.aiCourseCertificate.findMany({where:{...(from||to?{issuedAt:{...(from?{gte:new Date(from+"T00:00:00Z")} :{}),...(to?{lte:new Date(to+"T23:59:59.999Z")}: {})}}:{}),...(search?{OR:[{studentName:{contains:search}},{id:{contains:search}},{courseTitle:{contains:search}}]}:{}),...(["ACTIVE","REVOKED"].includes(status||"")?{status:status!}:{}),...(userId||courseId?{completion:{...(userId?{userId}:{}),...(courseId?{courseId}:{})}}:{})},include:{completion:true},orderBy:{issuedAt:"desc"},take:100});return NextResponse.json({certificates});}
export async function PATCH(req:NextRequest){const admin=await requireAdmin(req);if(!admin)return forbiddenResponse();const input=z.object({id:z.string(),reason:z.string().trim().min(10).max(2000)}).strict().safeParse(await req.json().catch(()=>null));if(!input.success)return NextResponse.json({error:"REVOCATION_REASON_REQUIRED"},{status:400});const record=await prisma.$transaction(async tx=>{const changed=await tx.aiCourseCertificate.updateMany({where:{id:input.data.id,status:"ACTIVE"},data:{status:"REVOKED",revokedAt:new Date(),revokedBy:admin.id,revocationReason:input.data.reason}});if(changed.count)await tx.auditLog.create({data:{actorId:admin.id,action:"academy_certificate_revoked",targetId:input.data.id,metadata:JSON.stringify({reason:input.data.reason})}});return tx.aiCourseCertificate.findUnique({where:{id:input.data.id}});});return record?NextResponse.json({certificate:record}):NextResponse.json({error:"NOT_FOUND"},{status:404});}
