export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { routedStreamChat } from "@/lib/ai/router";
import { isCronAuthorized } from "@/lib/auth/cronAuth";

// Hit by a system crontab entry, same shared-secret pattern as the other
// cron/* routes.
//
// Sales-chain phase 2.5, leak #1 (the biggest one found): a brand-new lead
// that never replied to the first message had nothing chasing it -- it just
// sat in the pipeline until the owner happened to notice. This runs a
// fixed follow-up cadence (day 2, day 5, day 10 with no CRM activity) and
// drafts a follow-up message at each step for the owner to review and send
// -- Draft-and-Approve, same as the post-viewing follow-up. After the last
// step with still no activity, it stops on its own rather than nagging
// forever.
const STEPS = [
  { day: 2, label: "پیگیری اول" },
  { day: 5, label: "پیگیری دوم" },
  { day: 10, label: "پیگیری سوم (آخر)" },
];

export async function GET(req: NextRequest) {
  if (!isCronAuthorized(req)) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  // Only leads that haven't progressed yet -- once qualified/customer, or
  // attached to a deal that moved past the first stage, the stage-change
  // task (crmRepository.moveDealToStage) already has this covered.
  const leads = await prisma.crmContact.findMany({
    where: { status: "lead" },
    select: { id: true, userId: true, name: true, notes: true, createdAt: true },
  });

  let drafted = 0;
  const errors: string[] = [];

  for (const lead of leads) {
    if (!lead.userId) continue;
    try {
      const lastActivity = await prisma.crmActivity.findFirst({
        where: { contactId: lead.id },
        orderBy: { createdAt: "desc" },
        select: { createdAt: true },
      });
      const since = lastActivity?.createdAt ?? lead.createdAt;
      const daysSince = Math.floor((Date.now() - since.getTime()) / 86400000);

      // The largest step whose threshold has been reached and hasn't been
      // drafted yet -- checked from largest to smallest so a lead that's
      // been silent for 12 days gets the "final" draft, not a redundant
      // day-2 one it already missed the window for.
      for (let i = STEPS.length - 1; i >= 0; i--) {
        const step = STEPS[i];
        if (daysSince < step.day) continue;

        const title = `${step.label}: ${lead.name} (${daysSince} روز بدون پاسخ)`;
        const existing = await prisma.crmTask.findFirst({ where: { userId: lead.userId, contactId: lead.id, title } });
        if (existing) break; // this step (or a later one already covers it) was already drafted

        let draft = "";
        await routedStreamChat(
          [{
            role: "user",
            content: `یک پیام پیگیری کوتاه و دوستانه (۲ تا ۳ جمله، فارسی) برای لید «${lead.name}» بنویس که ${daysSince} روز است پاسخی نداده. ${lead.notes ? `یادداشت قبلی درباره او: ${lead.notes}` : ""} لحن باید حرفه‌ای، غیرمصرانه و طبیعی باشد؛ این ${i + 1}اُمین پیام پیگیری است، پس تکراری به نظر نرسد.`,
          }],
          "تو دستیار فروش هستی و پیام‌های پیگیری لید سرد را می‌نویسی.",
          (chunk) => { draft += chunk; },
          () => {}
        );
        draft = draft.trim();
        if (draft) {
          await prisma.crmTask.create({ data: { userId: lead.userId, contactId: lead.id, title, autoGenerated: true, draftMessage: draft } });
          drafted++;
        }
        break; // one draft per lead per run, even if it qualifies for multiple steps
      }
    } catch (err) {
      errors.push(`lead ${lead.id}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return NextResponse.json({ leadsChecked: leads.length, drafted, errors });
}
