import { describe, it, expect } from "vitest";
import { parseProviderResult, providerPayload, seoRequestSchema, SeoProviderError } from "./provider";
import { seoConfigSchema, publicSeoConfig, quoteSeoAction } from "./config";
const config = seoConfigSchema.parse({ enabled: true, login: "encrypted-login", password: "encrypted-password", rates: { keywords: { baseUsd: 0.02, rowUsd: 0.001 }, rank: null, competitors: null, backlinks: null, referringDomains: null }, markupPercent: 20, infrastructureUsd: 0.01 });
describe("SEO provider boundaries", () => {
  it("does not expose credentials", () => { const safe = publicSeoConfig(config); expect(safe).not.toHaveProperty("password"); expect(safe).not.toHaveProperty("login"); expect(safe.configured).toBe(true); });
  it("requires explicit provider pricing and limits before execution", () => { expect(() => quoteSeoAction(config, "rank", 10)).toThrow("PRICING_NOT_CONFIGURED"); expect(() => quoteSeoAction(config, "keywords", 101)).toThrow("INVALID_ROW_LIMIT"); expect(quoteSeoAction(config, "keywords", 10).credits).toBe(5); });
  it("does not invent missing keyword metrics", () => { const result = parseProviderResult("keywords", { status_code: 20000, tasks: [{ status_code: 20000, cost: 0.02, result: [{ items: [{ keyword: "test", keyword_info: { search_volume: null } }] }] }] }); expect(result.actualCostUsd).toBe(0.02); expect(result.data).toEqual([{ keyword: "test", keyword_info: { search_volume: null } }]); });
  it("retains known expense when a provider task fails", () => { try { parseProviderResult("rank", { status_code: 20000, tasks: [{ status_code: 40101, cost: 0.003 }] }); throw Error("expected rejection"); } catch (error) { expect(error).toBeInstanceOf(SeoProviderError); expect((error as SeoProviderError).actualCostUsd).toBe(0.003); } });
  it("rejects malformed or negative expenses", () => { expect(() => parseProviderResult("keywords", { status_code: 20000, tasks: [{ status_code: 20000, cost: -1, result: [] }] })).toThrow("INVALID_PROVIDER_RESPONSE"); });
  it("does not allow provider paths, tenant or completion overrides", () => { expect(seoRequestSchema.safeParse({ action: "rank", siteId: "saved", keyword: "test", locationCode: 2840, languageCode: "en", endpoint: "http://localhost" }).success).toBe(false); });
  it("uses validated site domain and capped rank depth", () => { const input = seoRequestSchema.parse({ action: "rank", siteId: "saved", keyword: "test", locationCode: 2840, languageCode: "en" }); expect(providerPayload(input, "example.com")).toMatchObject({ keyword: "test", depth: 10, device: "desktop" }); });
  it("queries gaps in the correct direction using only organic evidence", () => { const input = seoRequestSchema.parse({ action: "keywordGap", siteId: "saved", competitorDomain: "competitor.com", locationCode: 2840, languageCode: "en" }); expect(providerPayload(input, "example.com")).toMatchObject({ target1: "competitor.com", target2: "example.com", intersections: false, item_types: ["organic"] }); });
  it("blocks unsupported ChatGPT markets before paying", () => { expect(seoRequestSchema.safeParse({ action: "aiVisibility", siteId: "saved", platform: "chat_gpt", locationCode: 2792, languageCode: "tr" }).success).toBe(false); });
  it("handles the observed provider 50000 envelope without inventing a task or expense", () => { try { parseProviderResult("rank", { status_code: 50000, cost: 0, tasks: null }); throw Error("expected failure"); } catch (error) { expect(error).toBeInstanceOf(SeoProviderError); expect((error as SeoProviderError).code).toBe("PROVIDER_SERVICE_UNAVAILABLE"); expect((error as SeoProviderError).actualCostUsd).toBe(0); } });
  it("requires an authoritative expense for successful results", () => { expect(() => parseProviderResult("keywords", { status_code: 20000, tasks: [{ status_code: 20000, cost: null, result: [{ items: [] }] }] })).toThrow("INVALID_PROVIDER_RESPONSE"); });
});
