import { getServerLang } from "@/lib/i18n/server";
import { copy, text, type Copy } from "@/lib/marketing/catalog";
import { pageMetadata, pageJsonLd } from "@/lib/seo/site";
import PublicShell from "@/components/marketing/PublicShell";
import JsonLd from "@/components/seo/JsonLd";
import Link from "next/link";
export const dynamic = "force-dynamic";
export async function generateMetadata() { const lang = await getServerLang(); return pageMetadata(lang, "/security", { fa: copy.security[0], en: copy.security[1], de: copy.security[2], tr: copy.security[3] }, { fa: copy.noPromise[0], en: copy.noPromise[1], de: copy.noPromise[2], tr: copy.noPromise[3] }); }
const sections: { title: Copy; body: Copy }[] = [
  { title: ["حساب و دسترسی", "Account & access", "Konto & Zugriff", "Hesap ve erişim"], body: ["فضاهای کاری نیازمند ورودند. دسترسی ابزارها براساس حساب، کسب‌وکار، نقش و ماژول فعال کنترل می‌شود. رمز عبور به‌صورت هش ذخیره می‌شود.", "Workspaces require sign-in. Access is controlled by account, business, role and enabled modules. Passwords are stored as hashes.", "Arbeitsbereiche erfordern Anmeldung. Zugriff wird nach Konto, Unternehmen, Rolle und Modulen kontrolliert. Passwörter werden als Hash gespeichert.", "Çalışma alanları giriş gerektirir. Erişim hesap, işletme, rol ve modüllere göre kontrol edilir. Parolalar karma olarak saklanır."] },
  { title: ["ارائه‌دهندگان AI", "AI providers", "KI-Anbieter", "Yapay zekâ sağlayıcıları"], body: ["برای پاسخ یا تولید، اطلاعات درخواست ممکن است به ارائه‌دهندهٔ مدل ارسال شود. دادهٔ حساس غیرضروری را وارد نکنید و سیاست حریم خصوصی را بررسی کنید.", "Request content may be sent to model providers to generate responses or media. Avoid unnecessary sensitive information and review our privacy policy.", "Anfrageinhalte können zur Generierung an Modellanbieter gesendet werden. Unnötige sensible Daten vermeiden und Datenschutzrichtlinie prüfen.", "Yanıt veya medya üretmek için istek içeriği model sağlayıcılara gönderilebilir. Gereksiz hassas bilgilerden kaçının ve gizlilik politikasını inceleyin."] },
  { title: ["اتصال‌های اختیاری", "Optional connections", "Optionale Verbindungen", "İsteğe bağlı bağlantılar"], body: ["اتصال اینستاگرام، وردپرس و منابع لید به مجوز شما و تنظیمات حساب وابسته است. قواعد و محدودیت‌های سرویس خارجی همچنان اعمال می‌شوند.", "Instagram, WordPress and lead-source connections depend on your permission and account setup. External service rules and limits still apply.", "Instagram-, WordPress- und Lead-Verbindungen hängen von Berechtigungen und Einrichtung ab. Regeln und Limits der Anbieter gelten weiterhin.", "Instagram, WordPress ve kaynak bağlantıları izinlerinize ve hesap kurulumuna bağlıdır. Dış servis kuralları ve sınırları geçerlidir."] },
  { title: ["مسئولیت بررسی خروجی", "Review before acting", "Vor Aktionen prüfen", "İşlemden önce inceleyin"], body: ["این صفحه ادعای گواهی امنیتی، تضمین uptime یا انطباق حقوقی نمی‌کند. خروجی AI ممکن است خطا داشته باشد؛ تصمیم مالی، انتشار و پیام‌رسانی را بررسی کنید.", "This page makes no security certification, uptime or legal compliance guarantee. AI can make mistakes; review financial decisions, publishing and messaging.", "Diese Seite garantiert keine Sicherheitszertifizierung, Verfügbarkeit oder Rechtskonformität. KI kann Fehler machen; Finanzen, Veröffentlichung und Nachrichten prüfen.", "Bu sayfa güvenlik sertifikası, çalışma süresi veya yasal uyum garantisi vermez. Yapay zekâ hata yapabilir; mali kararları, yayınları ve mesajları inceleyin."] },
];
export default async function SecurityPage() { const lang = await getServerLang(); return <PublicShell lang={lang}><JsonLd data={pageJsonLd(lang, "/security")}/><section className="m-detail-hero"><div className="m-container"><span className="m-eyebrow">AIFekr</span><h1>{text(lang, copy.security)}</h1></div></section><section className="m-container m-section m-prose">{sections.map(s => <article key={s.title[1]}><h2>{text(lang, s.title)}</h2><p>{text(lang, s.body)}</p></article>)}<div className="m-actions"><Link className="m-button m-secondary" href="/privacy">{text(lang, copy.privacy)}</Link><Link className="m-button m-secondary" href="/contact">{text(lang, copy.contact)}</Link></div></section></PublicShell>; }
