/** New offer has a distinct code so existing two-month purchases keep their terms. */
export const STUDENT_PLAN_CODE = "STUDENT_FIRST_THREE_MONTHS";
export const LEGACY_STUDENT_PLAN_CODE = "STUDENT_FIRST_TWO_MONTHS";
export const STUDENT_MONTHLY_CODE = "STUDENT_MONTHLY";
export const STUDENT_OFFER = { usdPrice: 80, originalUsdPrice: 240, months: 3, days: 90 };
export const isStudentIntroPlan = (plan: string) => [STUDENT_PLAN_CODE, LEGACY_STUDENT_PLAN_CODE].includes(plan);
export function studentOfferPrices(usdToToman: number, usdToTry: number, usdCents = 8000) {
  return { usdCents, toman: Math.round(usdCents / 100 * usdToToman), lira: Math.round(usdCents / 100 * usdToTry * 100) / 100 };
}
type StudentLanguage = "fa" | "en" | "de" | "tr";
export const studentOfferCopy: Record<StudentLanguage, { title: string; period: string; buy: string; rate: string; credit: string; features: string[] }> = {
  fa: { title: "پکیج دانشجویی", period: "۳ ماه (۹۰ روز) فقط ۸۰ دلار برای کل دوره؛ قیمت عادی سه ماه ۲۴۰ دلار", buy: "خرید پکیج دانشجویی", rate: "معادل‌ها با نرخ مرجع روز محاسبه می‌شوند؛ مبلغ پرداخت در مرحلهٔ خرید تأیید می‌شود.", credit: "مصرف ابزارهای AI کردیت لازم دارد؛ کردیت اضافی جداگانه خریداری می‌شود.", features: ["داشبورد و دسته‌بندی درس‌ها، جزوه‌ها و یادداشت‌ها", "برنامهٔ مطالعه و مدیریت تکلیف‌ها و امتحان‌ها", "زمان‌سنج، توقف و گزارش مطالعه برای استاد", "گروه مطالعه و دعوت با ایمیل", "پروفایل و کارت دانشجویی قابل اشتراک", "گفتگوی درسی، فلش‌کارت و آزمون با AI", "OCR تصویر و PPTX و رونویسی صوت با مصرف کردیت", "کمک پژوهش و پایان‌نامه با مصرف کردیت"] },
  en: { title: "Student package", period: "3 months (90 days) for only $80 total; regular three-month price $240", buy: "Get the student package", rate: "Equivalents use the current reference exchange rate; the payable amount is confirmed at checkout.", credit: "AI tools require credits; additional credits are purchased separately.", features: ["Course, material and note workspace", "Study planning, assignments and exams", "Study timer, pauses and instructor reports", "Study groups and email invitations", "Shareable student profile and card", "AI course chat, flashcards and quizzes", "Image/PPTX OCR and audio transcription using credits", "Research and thesis assistance using credits"] },
  de: { title: "Studierendenpaket", period: "3 Monate (90 Tage) für insgesamt nur 80 USD; regulärer Dreimonatspreis 240 USD", buy: "Studierendenpaket kaufen", rate: "Umrechnungen basieren auf dem aktuellen Referenzkurs; der Zahlbetrag wird beim Checkout bestätigt.", credit: "KI-Werkzeuge benötigen Credits; zusätzliche Credits werden separat gekauft.", features: ["Arbeitsbereich für Kurse, Materialien und Notizen", "Lernplanung, Aufgaben und Prüfungen", "Lernzeit-Timer, Pausen und Berichte für Lehrende", "Lerngruppen und Einladungen per E-Mail", "Teilbares Studierendenprofil und Karte", "KI-Kurschat, Lernkarten und Quiz", "Bild/PPTX-OCR und Audiotranskription mit Credits", "Recherche- und Abschlussarbeitshilfe mit Credits"] },
  tr: { title: "Öğrenci paketi", period: "3 ay (90 gün) için toplam yalnızca 80 USD; normal üç aylık fiyat 240 USD", buy: "Öğrenci paketini al", rate: "Karşılıklar güncel referans kura göre hesaplanır; ödenecek tutar ödeme adımında onaylanır.", credit: "Yapay zekâ araçları kredi gerektirir; ek krediler ayrıca satın alınır.", features: ["Ders, materyal ve not çalışma alanı", "Çalışma planı, ödev ve sınav yönetimi", "Çalışma sayacı, duraklamalar ve öğretim görevlisi raporları", "Çalışma grupları ve e-posta davetleri", "Paylaşılabilir öğrenci profili ve kartı", "Yapay zekâ ders sohbeti, bilgi kartları ve testler", "Krediyle görsel/PPTX OCR ve ses transkripsiyonu", "Krediyle araştırma ve tez desteği"] },
};
