"use client";
import {useState} from "react";
import {tri,useTranslation} from "@/lib/i18n";
import type {Lang} from "@/lib/i18n";
const languages:{code:Lang;name:string;instruction:string}[]=[{code:"fa",name:"فارسی",instruction:"ورود به فضای کار به زبان فارسی"},{code:"en",name:"English",instruction:"Enter your workspace in English"},{code:"tr",name:"Türkçe",instruction:"Çalışma alanına Türkçe giriş yap"},{code:"de",name:"Deutsch",instruction:"Arbeitsbereich auf Deutsch öffnen"}];
export default function WelcomeLanguage(){
 const {lang}=useTranslation(),[selected,setSelected]=useState<Lang>(lang),[busy,setBusy]=useState(false),[error,setError]=useState(''),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr);
 async function continueOnboarding(){setBusy(true);setError('');try{const response=await fetch('/api/user/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:selected})});if(!response.ok)throw Error();document.cookie=`lang=${selected}; path=/; max-age=31536000; SameSite=Lax`;localStorage.setItem('lang',selected);const url=new URL(window.location.href);url.searchParams.set('langChosen','1');window.location.href=url.pathname+url.search;}catch{setError(t("زبان ذخیره نشد؛ دوباره تلاش کن","Could not save language; please retry","Sprache konnte nicht gespeichert werden; erneut versuchen","Dil kaydedilemedi; tekrar dene"));setBusy(false);}}
 return <main dir={lang==='fa'?'rtl':'ltr'} className="flex min-h-screen items-center justify-center bg-[#0a0a0f] p-5 text-white"><section className="w-full max-w-xl rounded-3xl border border-white/10 bg-white/5 p-6 sm:p-10"><p className="mb-5 text-orange-400">AIFekr</p><h1 className="text-2xl font-bold">{t("با چه زبانی وارد فضای کار می‌شوی؟","Which language would you like to use?","Welche Sprache möchtest du verwenden?","Hangi dili kullanmak istersin?")}</h1><p className="mt-3 text-sm leading-7 text-white/70">Choose your language · زبانت را انتخاب کن · Dilini seç · Sprache wählen</p><fieldset disabled={busy} className="mt-7 grid gap-3 sm:grid-cols-2"><legend className="sr-only">{t("زبان فضای کار","Workspace language","Sprache des Arbeitsbereichs","Çalışma alanı dili")}</legend>{languages.map(l=><label key={l.code} className={`flex cursor-pointer items-start gap-3 rounded-2xl border p-4 ${selected===l.code?'border-orange-500 bg-orange-500/10':'border-white/15'}`}><input className="mt-1 accent-orange-500" type="radio" name="workspace-language" value={l.code} checked={selected===l.code} onChange={()=>setSelected(l.code)}/><span dir={l.code==='fa'?'rtl':'ltr'}><strong>{l.name}</strong><span className="mt-2 block text-xs leading-6 text-white/70">{l.instruction}</span></span></label>)}</fieldset><p className="mt-5 text-sm text-white/60">{t("بعداً از تنظیمات می‌توانی زبان را تغییر بدهی.","You can change this later in Settings.","Du kannst die Sprache später in den Einstellungen ändern.","Dili daha sonra Ayarlar bölümünden değiştirebilirsin.")}</p><button disabled={busy} onClick={()=>void continueOnboarding()} className="mt-6 min-h-12 w-full rounded-xl bg-orange-600 px-5 py-3 font-semibold disabled:opacity-50">{busy?'…':languages.find(l=>l.code===selected)?.instruction}</button>{error&&<p role="alert" className="mt-4 text-red-300">{error}</p>}</section></main>;
}
