"use client";
import {useEffect,useState} from "react";
import AcademyImageUpload from "./AcademyImageUpload";
import BlueprintEditor from "./BlueprintEditor";
import CompletionSettings from "./CompletionSettings";
import {tri,useTranslation} from "@/lib/i18n";
type Meta={coverUrl:string|null;difficulty:string;durationMinutes:number;topic:string;skills:string;prerequisites:string;configuration:string;blueprint:string|null;status:string;version:number;activeJobId:string|null};
export default function AcademyCourseSettings({id,refresh}:{id:string;refresh:()=>Promise<void>}){
 const {lang}=useTranslation(),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr),[course,setCourse]=useState<Meta|null>(null),[majors,setMajors]=useState<{id:string;name:string}[]>([]),[selected,setSelected]=useState<string[]>([]),[config,setConfig]=useState(''),[blueprint,setBlueprint]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const [a,b]=await Promise.all([fetch(`/api/admin/ai-courses/${id}`).then(r=>r.json()),fetch('/api/admin/academy/majors').then(r=>r.json())]);setCourse(a.course);setConfig(JSON.stringify(JSON.parse(a.course.configuration),null,2));setBlueprint(a.course.blueprint?JSON.stringify(JSON.parse(a.course.blueprint),null,2):'');setSelected((a.course.majors||[]).map((m:{majorId:string})=>m.majorId));setMajors(b.majors||[]);}
 useEffect(()=>{void load().catch(()=>setMessage('LOAD_FAILED'));},[id]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!course?.activeJobId||course.status==="BLUEPRINT_REVIEW")return;const timer=setInterval(()=>{void load();},5000);return()=>clearInterval(timer);},[id,course?.activeJobId]); // eslint-disable-line react-hooks/exhaustive-deps
 async function save(){if(!course)return;setBusy(true);try{const r=await fetch(`/api/admin/ai-courses/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:course.version,coverUrl:course.coverUrl,difficulty:course.difficulty,durationMinutes:course.durationMinutes,topic:course.topic,skills:course.skills.startsWith('[')?JSON.parse(course.skills):course.skills.split('\n').filter(Boolean),prerequisites:course.prerequisites,configuration:JSON.parse(config),majorIds:selected})});if(!r.ok)throw Error((await r.json()).error);await load();await refresh();setMessage(t('ذخیره شد','Saved','Gespeichert','Kaydedildi'));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function approve(cancel=false){setBusy(true);try{const r=await fetch(`/api/admin/ai-courses/${id}/blueprint`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true,cancel,blueprint:cancel?null:JSON.parse(blueprint)})});if(!r.ok)throw Error((await r.json()).error);await load();await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!course)return null;const input='min-h-12 w-full rounded-xl border border-slate-500/30 bg-transparent p-3';
 return <section className="space-y-5 rounded-2xl border border-slate-500/30 p-5"><h2 className="text-xl font-semibold">{t('تنظیمات آکادمی','Academy configuration','Akademie-Einstellungen','Akademi ayarları')}</h2><fieldset disabled={busy||!!course.activeJobId} className="grid gap-4 sm:grid-cols-2"><fieldset><legend>{t('رشته‌های هدف','Target majors','Zielstudienfächer','Hedef bölümler')}</legend><div className="mt-2 max-h-48 overflow-y-auto rounded-xl border border-slate-500/30 p-3">{majors.map(m=><label className="flex min-h-11 items-center gap-3" key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/>{m.name}</label>)}</div></fieldset><label>{t("سطح دوره","Difficulty","Schwierigkeitsgrad","Zorluk")}<select className={input} value={course.difficulty} onChange={e=>setCourse({...course,difficulty:e.target.value})}>{['BEGINNER','INTERMEDIATE','ADVANCED'].map(v=><option key={v}>{v}</option>)}</select></label><label>{t("مدت دوره (دقیقه)","Duration (minutes)","Dauer (Minuten)","Süre (dakika)")}<input className={input} type="number" min={5} max={60000} value={course.durationMinutes} onChange={e=>setCourse({...course,durationMinutes:Number(e.target.value)})}/></label><label>{t("موضوع","Topic","Thema","Konu")}<input className={input} value={course.topic} onChange={e=>setCourse({...course,topic:e.target.value})}/></label><label>{t("مهارت‌ها — هر خط یک مورد","Skills (one per line)","Fähigkeiten (eine pro Zeile)","Beceriler (satır başına bir)")}<textarea className={input} value={course.skills.startsWith('[')?JSON.parse(course.skills).join('\n'):course.skills} onChange={e=>setCourse({...course,skills:e.target.value})}/></label><label>{t("پیش‌نیازها","Prerequisites","Voraussetzungen","Ön koşullar")}<textarea className={input} value={course.prerequisites} onChange={e=>setCourse({...course,prerequisites:e.target.value})}/></label><label>{t("تصویر کاور (HTTPS)","Cover image (HTTPS)","Titelbild (HTTPS)","Kapak görseli (HTTPS)")}<input className={input} type="url" value={course.coverUrl||""} onChange={e=>setCourse({...course,coverUrl:e.target.value||null})}/></label><div><AcademyImageUpload onUploaded={url=>setCourse({...course,coverUrl:url})}/></div><CompletionSettings value={config} onChange={setConfig}/><details className="sm:col-span-2"><summary>Advanced JSON</summary><label>{t('اهداف، سبک تدریس و قوانین تکمیل — JSON','Audience, teaching style & completion rules — JSON','Zielgruppe, Unterrichtsstil & Abschlussregeln — JSON','Hedef kitle, öğretim stili ve tamamlama kuralları — JSON')}<textarea dir="ltr" rows={14} className={input+' font-mono text-sm'} value={config} onChange={e=>setConfig(e.target.value)}/></label></details><button type="button" className="rounded-xl border px-5 py-3" onClick={()=>void save()}>{t('ذخیره تنظیمات — رایگان','Save settings · free','Einstellungen speichern · kostenlos','Ayarları kaydet · ücretsiz')}</button></fieldset>
 {course.status==='BLUEPRINT_REVIEW'&&<section className="space-y-4 border-t border-orange-500/30 pt-5"><h3 className="font-bold">{t('بازبینی طرح درس قبل از تولید محتوا','Review blueprint before lesson generation','Lehrplan vor Generierung prüfen','İçerik üretiminden önce planı incele')}</h3><p className="text-sm leading-7">{t('اعتبار رزرو شده است. تأیید طرح هزینهٔ دوباره ندارد. در صورت لغو یا انقضا اعتبار برمی‌گردد.','Credits are reserved. Approval has no second charge. Cancel or expiry releases credits.','Credits sind reserviert. Genehmigung kostet nicht erneut. Abbruch oder Ablauf erstattet Credits.','Krediler ayrıldı. Onay ek ücret almaz. İptal veya süre dolması kredileri iade eder.')}</p><BlueprintEditor value={blueprint} onChange={setBlueprint}/><details><summary>Advanced JSON</summary><textarea aria-label="Blueprint JSON" dir="ltr" rows={18} className={input+' font-mono text-sm'} value={blueprint} onChange={e=>setBlueprint(e.target.value)}/></details><div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-xl bg-orange-500 px-5 py-3 text-white" onClick={()=>void approve()}>{t('طرح را تأیید می‌کنم؛ تولید درس‌ها','Approve blueprint & generate lessons','Lehrplan genehmigen & Lektionen erstellen','Planı onayla ve dersleri oluştur')}</button><button disabled={busy} className="rounded-xl border px-5 py-3" onClick={()=>void approve(true)}>{t('لغو و بازگشت اعتبار','Cancel & refund','Abbrechen & erstatten','İptal ve iade')}</button></div></section>}<p role="status">{message}</p></section>;
}
