"use client";
import {useEffect,useRef,useState,useCallback} from "react";
import {tri,useTranslation} from "@/lib/i18n";
export default function CourseNotes({courseId,lessonId}:{courseId:string;lessonId:string}){
 const {lang}=useTranslation(),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr),[value,setValue]=useState(""),[loaded,setLoaded]=useState(false),[loadAttempt,setLoadAttempt]=useState(0),[state,setState]=useState("loading"),current=useRef(""),dirty=useRef(false),saving=useRef<Promise<void>|null>(null);
 const url=`/api/learn/courses/${courseId}/notes?lesson=${encodeURIComponent(lessonId)}`;
 const save=useCallback(()=>{if(saving.current)return saving.current;const work=(async()=>{setState("saving");while(dirty.current){const content=current.current;dirty.current=false;try{const r=await fetch(url,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({content}),keepalive:true});if(!r.ok)throw Error();}catch{dirty.current=true;setState("error");return;}}setState("saved");})();saving.current=work;void work.finally(()=>{saving.current=null;});return work;},[url]);
 useEffect(()=>{let active=true;fetch(url).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(active){current.current=d.note?.content||"";setValue(current.current);setLoaded(true);setState("saved");}}).catch(()=>{if(active)setState("loadError");});return()=>{active=false;};},[url,loadAttempt]);
 useEffect(()=>{if(!loaded||!dirty.current)return;const timer=setTimeout(()=>{void save();},800);return()=>clearTimeout(timer);},[value,loaded,save]);
 useEffect(()=>{const flush=()=>{if(dirty.current)void save();};window.addEventListener("pagehide",flush);return()=>{window.removeEventListener("pagehide",flush);flush();};},[save]);
 return <div className="mt-3 space-y-3"><textarea disabled={!loaded} aria-label={t("یادداشت همین درس","Notes for this lesson","Notizen zu dieser Lektion","Bu ders için notlar")} value={value} maxLength={20000} onChange={e=>{current.current=e.target.value;dirty.current=true;setValue(e.target.value);setState("pending");}} className="min-h-48 w-full rounded-lg border bg-transparent p-3"/><p role="status" className="text-xs text-slate-400">{state==="saved"?t("ذخیره در حساب؛ در دستگاه‌های دیگر هم در دسترس است","Saved to your account; available on other devices","Im Konto gespeichert; geräteübergreifend verfügbar","Hesabına kaydedildi; diğer cihazlarda kullanılabilir"):state==="error"||state==="loadError"?t("ذخیره یا دریافت نشد؛ دوباره تلاش کن","Could not save or load; retry","Speichern oder Laden fehlgeschlagen; erneut versuchen","Kaydetme veya yükleme başarısız; tekrar dene"):t("در حال ذخیره / دریافت…","Saving / loading…","Speichern / Laden…","Kaydediliyor / yükleniyor…")}</p>{(state==="error"||state==="loadError")&&<button className="min-h-11 rounded-lg border px-3" onClick={()=>{if(state==="loadError"){setState("loading");setLoadAttempt(n=>n+1);}else void save();}}>{t("تلاش دوباره","Retry","Erneut versuchen","Tekrar dene")}</button>}</div>;
}
