"use client";
import {useEffect,useState} from "react";
import {courseContentSchema,CourseContent} from "@/lib/courses/content";
import StructuredCourseEditor from "./StructuredCourseEditor";
import LearningBlocks from "./LearningBlocks";
import {useTranslation,tri} from "@/lib/i18n";
export default function CourseSourceEditor({content,disabled,change}:{content:CourseContent;disabled:boolean;change:(c:CourseContent)=>void}){
 const {lang}=useTranslation(),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr),[source,setSource]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 useEffect(()=>{setSource(JSON.stringify(content,null,2));},[content]);
 function apply(){try{change(courseContentSchema.parse(JSON.parse(source)));setError('');}catch{setError(t('ساختار محتوا معتبر نیست؛ تغییری اعمال نشد.','Invalid content structure; no change applied.','Ungültige Struktur; keine Änderung.','Geçersiz yapı; değişiklik uygulanmadı.'));}}
 async function upload(file?:File){if(!file)return;try{const form=new FormData();form.set('file',file);const response=await fetch('/api/admin/academy/media',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error);await navigator.clipboard.writeText(data.url);setError(t('آدرس تصویر کپی شد؛ در بلوک image همراه با alt و caption وارد کن.','Image URL copied; add it to an image block with alt and caption.','Bild-URL kopiert; mit Alt-Text und Bildunterschrift einfügen.','Resim URL kopyalandı; alt metin ve açıklamayla resim bloğuna ekle.'));}catch(e){setError((e as Error).message);}}
 return <details className="rounded-2xl border border-slate-500/30 p-5"><summary className="cursor-pointer font-semibold">{t('ویرایش کامل بلوک‌ها، ساختار و آزمون نهایی / پیش‌نمایش','Full blocks, curriculum & final assessment editor / preview','Editor für Blöcke, Lehrplan & Abschlussprüfung / Vorschau','Bloklar, müfredat ve final değerlendirme düzenleyicisi / önizleme')}</summary><p className="my-4 text-sm leading-7">{t('ترتیب، اضافه‌کردن و حذف فصل‌ها، درس‌ها، بلوک‌ها و سؤال‌ها در ساختار JSON قابل ویرایش است. سپس اعمال و ذخیره کن.','Reorder, add and remove chapters, lessons, blocks and questions in the JSON structure. Apply, then save.','Kapitel, Lektionen, Blöcke und Fragen in JSON hinzufügen, entfernen und sortieren. Anwenden und speichern.','JSON yapısında bölümleri, dersleri, blokları ve soruları ekle, sil ve sırala. Uygula, sonra kaydet.')}</p><label className="my-4 block">Upload / replace course image<input disabled={disabled} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])} className="mt-2 block"/></label><StructuredCourseEditor content={content} disabled={disabled} change={change}/><details><summary>Advanced JSON</summary><textarea disabled={disabled} aria-label="Structured course content" dir="ltr" rows={20} className="w-full rounded-xl border border-slate-500/30 bg-transparent p-4 font-mono text-sm" value={source} onChange={e=>setSource(e.target.value)}/></details><div className="my-4 flex gap-3"><button disabled={disabled} className="rounded-lg border px-4 py-3" onClick={apply}>{t('اعمال ویرایش — رایگان','Apply edits · free','Änderungen anwenden · kostenlos','Değişiklikleri uygula · ücretsiz')}</button><button className="rounded-lg border px-4 py-3" onClick={()=>setPreview(!preview)}>{t('پیش‌نمایش','Preview','Vorschau','Önizleme')}</button></div>{error&&<p role="alert">{error}</p>}{preview&&content.chapters.map((c,i)=><section key={i} className="mt-8"><h3 className="text-xl font-bold">{c.title}</h3>{c.lessons.map((l,j)=><article key={j} className="mt-5 space-y-4 rounded-xl border border-slate-500/30 p-5"><h4 className="text-lg font-semibold">{l.title}</h4><LearningBlocks blocks={l.blocks} fallback={l.content}/><p className="leading-7">{l.activity}</p></article>)}</section>)}</details>;
}
