"use client";
import {useState,useEffect} from "react";
import {tri,useTranslation} from "@/lib/i18n";
type Revision={id:string;version:number;createdAt:string;reason:string};
export default function CourseRevisionHistory({id,version,disabled,refresh}:{id:string;version:number;disabled:boolean;refresh:()=>Promise<void>}){
 const {lang}=useTranslation(),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr),[rows,setRows]=useState<Revision[]>([]),[selected,setSelected]=useState<string|null>(null),[preview,setPreview]=useState(""),[confirm,setConfirm]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{setSelected(null);setPreview("");setConfirm(false);fetch(`/api/admin/ai-courses/${id}/revisions`).then(async r=>{if(!r.ok)throw Error("REVISION_LOAD_FAILED");setRows((await r.json()).revisions);}).catch(e=>setError(e.message));},[id,version]);
 async function choose(row:Revision){setSelected(row.id);setConfirm(false);setPreview("");try{const r=await fetch(`/api/admin/ai-courses/${id}/revisions?revision=${encodeURIComponent(row.id)}`);if(!r.ok)throw Error("REVISION_LOAD_FAILED");const d=await r.json();setPreview(JSON.stringify({metadata:JSON.parse(d.revision.metadata),content:JSON.parse(d.revision.content)},null,2));}catch(e){setError((e as Error).message);}}
 async function restore(){if(!selected||!confirm)return;setBusy(true);try{const r=await fetch(`/api/admin/ai-courses/${id}/revisions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revisionId:selected,version,confirm:true})});if(!r.ok)throw Error((await r.json()).error);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="rounded-2xl border border-slate-500/30 p-5"><summary className="cursor-pointer font-semibold">{t("تاریخچه و بازگردانی پیش‌نویس","Draft history & restore","Entwurfsverlauf & Wiederherstellung","Taslak geçmişi ve geri yükleme")}</summary><div className="mt-4 flex flex-wrap gap-3">{rows.map(r=><button key={r.id} className="min-h-11 rounded-lg border px-3 py-2" onClick={()=>void choose(r)}>v{r.version} · {r.createdAt.slice(0,10)}</button>)}</div>{!rows.length&&<p className="mt-4 text-sm">{t("هنوز ویرایش قبلی ثبت نشده است","No earlier revisions yet","Noch keine früheren Revisionen","Henüz önceki sürüm yok")}</p>}{preview&&<><pre dir="ltr" className="my-4 max-h-96 overflow-auto whitespace-pre-wrap break-all rounded-xl border p-4 text-xs">{preview}</pre><label className="flex items-start gap-3 leading-7"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} className="mt-2"/>{t("این بازبینی را به‌عنوان پیش‌نویس جدید بازگردان. انتشار دوباره نیاز به تأیید من دارد و نسخهٔ دانشجویان قبلی حفظ می‌شود.","Restore this revision as a new draft. Publication requires review again; existing student versions remain preserved.","Als neuen Entwurf wiederherstellen. Veröffentlichung erfordert erneute Prüfung; bestehende Lernversionen bleiben erhalten.","Yeni taslak olarak geri yükle. Yayınlama yeniden inceleme gerektirir; öğrencilerin mevcut sürümleri korunur.")}</label><button disabled={disabled||busy||!confirm} className="mt-4 min-h-12 rounded-xl border px-4 py-3 disabled:opacity-40" onClick={()=>void restore()}>{t("بازگردانی — رایگان","Restore · free","Wiederherstellen · kostenlos","Geri yükle · ücretsiz")}</button></>}{error&&<p role="alert">{error}</p>}</details>;
}
