"use client";
import {useTranslation,tri} from "@/lib/i18n";
import {useState} from "react";
import type {z} from "zod";
import type {learningBlockSchema} from "@/lib/courses/content";
type Block=z.infer<typeof learningBlockSchema>;
function Exercise({block}:{block:Extract<Block,{prompt:string}>}){const {lang}=useTranslation();const [answer,setAnswer]=useState(""),[show,setShow]=useState(false);return <section className="my-6 rounded-xl border border-orange-500/20 p-5"><h4 className="font-semibold">{block.prompt}</h4><textarea aria-label={block.prompt} value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-4 min-h-24 w-full rounded-lg border border-slate-500/30 bg-transparent p-3"/><button className="mt-3 rounded-lg border px-4 py-2" onClick={()=>setShow(!show)}>{tri(lang,"نمایش / پنهان‌کردن توضیح","Show / hide explanation","Erklärung anzeigen / ausblenden","Açıklamayı göster / gizle")}</button>{show&&<p className="mt-4 leading-7">{block.answer}</p>}</section>;}
function embedUrl(url:string){try{const u=new URL(url);let id:string|null=null;if(["www.youtube.com","youtube.com","m.youtube.com"].includes(u.hostname))id=u.pathname.startsWith("/embed/")?u.pathname.split("/")[2]:u.searchParams.get("v");if(u.hostname==="youtu.be")id=u.pathname.slice(1);if(id&&/^[a-zA-Z0-9_-]{11}$/.test(id))return `https://www.youtube-nocookie.com/embed/${id}`;if(["vimeo.com","www.vimeo.com","player.vimeo.com"].includes(u.hostname)){const v=u.pathname.split("/").filter(Boolean).pop();if(v&&/^\d+$/.test(v))return `https://player.vimeo.com/video/${v}`;}}catch{}return null;}
export default function LearningBlocks({blocks,fallback}:{blocks?:Block[];fallback:string}){if(!blocks?.length)return <div className="space-y-5">{fallback.split(/\n\s*\n/).map((text,i)=><p key={i} className="whitespace-pre-wrap leading-8">{text}</p>)}</div>;return <div className="space-y-6">{blocks.map((b,i)=>{
 if("prompt" in b)return <Exercise key={i} block={b}/>;
 if(b.type==="heading")return <h4 key={i} className="pt-3 text-xl font-semibold">{b.text}</h4>;
 if(b.type==="code")return <pre key={i} dir="ltr" className="overflow-x-auto rounded-xl bg-[var(--surface-2)] p-5 text-sm leading-7 text-[var(--text-primary)]"><code style={{color:"var(--text-primary)",background:"transparent"}}>{b.code}</code></pre>;
 if(b.type==="table")return <div key={i} className="overflow-x-auto"><table className="w-full text-start"><thead><tr>{b.headers.map((h,j)=><th className="border-b p-3 text-start" key={j}>{h}</th>)}</tr></thead><tbody>{b.rows.map((row,j)=><tr key={j}>{row.map((v,k)=><td key={k} className="border-b border-slate-500/20 p-3">{v}</td>)}</tr>)}</tbody></table></div>;
 if("url" in b){if(b.type==="videoEmbed"){const url=embedUrl(b.url);if(url)return <figure key={i}><iframe title={b.alt} src={url} loading="lazy" sandbox="allow-scripts allow-same-origin allow-presentation" allowFullScreen className="aspect-video w-full rounded-xl border-0"/><figcaption className="mt-2 text-sm text-slate-400">{b.caption}</figcaption></figure>;}if(b.type==="image")return <figure key={i}><img src={b.url} alt={b.alt} loading="lazy" className="max-h-96 w-full rounded-xl object-contain"/><figcaption className="mt-2 text-sm text-slate-400">{b.caption}</figcaption></figure>;return <a key={i} href={b.url} target="_blank" rel="noopener noreferrer" className="block rounded-xl border border-slate-500/30 p-4 text-orange-400">{b.alt} ↗</a>;}
 if("items" in b)return b.type==="flashcards"?<div key={i} className="grid gap-3 sm:grid-cols-2">{b.items.map((v,j)=><details key={j} className="rounded-xl border border-slate-500/30 p-4"><summary className="cursor-pointer">{v.split("::")[0]}</summary><p className="mt-3 leading-7">{v.split("::").slice(1).join("::")||v}</p></details>)}</div>:<ol key={i} className="list-inside list-decimal space-y-3">{b.items.map((v,j)=><li key={j} className="leading-7">{v}</li>)}</ol>;
 if("text" in b)return <p key={i} className={`whitespace-pre-wrap leading-8 ${["tip","keyConcept","warning","callout","summary"].includes(b.type)?"rounded-xl border-s-2 border-orange-500 bg-orange-500/5 p-5":""}`}>{b.text}</p>;return null;
})}</div>;}
