"use client";
import AcademyImageUpload from "./AcademyImageUpload";
import {useState} from "react";
import type {CourseContent} from "@/lib/courses/content";
import {tri,useTranslation} from "@/lib/i18n";
export default function StructuredCourseEditor({content,disabled,change}:{content:CourseContent;disabled:boolean;change:(c:CourseContent)=>void}){
 const {lang}=useTranslation(),t=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr),[ci,setCi]=useState(0),[li,setLi]=useState(0),[blockType,setBlockType]=useState("paragraph");
 const chapter=content.chapters[ci]||content.chapters[0],lesson=chapter.lessons[li]||chapter.lessons[0],field="min-h-12 w-full rounded-lg border border-slate-500/30 bg-transparent p-3",button="min-h-11 rounded-lg border px-3 py-2 disabled:opacity-40";
 function edit(fn:(c:CourseContent)=>void){const c=structuredClone(content);fn(c);change(c);}
 const move=<T,>(items:T[],i:number,d:number)=>{if(i+d<0||i+d>=items.length)return;[items[i],items[i+d]]=[items[i+d],items[i]];};
 function addBlock(){edit(c=>{const l=c.chapters[ci].lessons[li];const blocks=l.blocks||(l.blocks=[{type:"paragraph",text:l.content},{type:"summary",text:l.activity}]);switch(blockType){case "code":blocks.push({type:"code",code:"// Add a reviewed code example",language:"javascript"});break;case "steps":case "flashcards":blocks.push({type:blockType,items:["Edit this learning item"]});break;case "table":blocks.push({type:"table",headers:["Heading"],rows:[["Value"]]});break;case "image":blocks.push({type:"image",url:"",alt:"Replace with an uploaded image and accurate alt text"});break;case "knowledgeCheck":blocks.push({type:"knowledgeCheck",prompt:"Edit the practice question",answer:"Edit its explanation"});break;default:blocks.push({type:blockType as "paragraph",text:"Edit this draft block before publishing"});}});}
 return <fieldset disabled={disabled} className="my-5 space-y-5"><label className="block">{t("معرفی دوره","Course overview","Kursübersicht","Kurs özeti")}<textarea className={field} rows={4} value={content.overview} onChange={e=>edit(c=>{c.overview=e.target.value;})}/></label>
 <label className="block">{t("هدف‌های یادگیری؛ هر خط یک مورد","Learning objectives (one per line)","Lernziele (eines pro Zeile)","Öğrenme hedefleri (satır başına bir)")}<textarea className={field} value={content.objectives.join("\n")} onChange={e=>edit(c=>{c.objectives=e.target.value.split("\n");})}/></label>
 <div className="grid gap-4 sm:grid-cols-2"><label>{t("فصل","Chapter","Kapitel","Bölüm")}<select className={field} value={ci} onChange={e=>{setCi(Number(e.target.value));setLi(0);}}>{content.chapters.map((c,i)=><option key={i} value={i}>{i+1}. {c.title}</option>)}</select></label><label>{t("درس","Lesson","Lektion","Ders")}<select className={field} value={li} onChange={e=>setLi(Number(e.target.value))}>{chapter.lessons.map((l,i)=><option key={i} value={i}>{i+1}. {l.title}</option>)}</select></label></div>
 <label className="block">{t("عنوان فصل","Chapter title","Kapiteltitel","Bölüm başlığı")}<input className={field} value={chapter.title} onChange={e=>edit(c=>{c.chapters[ci].title=e.target.value;})}/></label>
 <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={ci===0} onClick={()=>{edit(c=>move(c.chapters,ci,-1));setCi(ci-1);}}>↑ {t("فصل","Chapter","Kapitel","Bölüm")}</button><button type="button" className={button} disabled={ci===content.chapters.length-1} onClick={()=>{edit(c=>move(c.chapters,ci,1));setCi(ci+1);}}>↓ {t("فصل","Chapter","Kapitel","Bölüm")}</button><button type="button" className={button} disabled={content.chapters.length>=12} onClick={()=>{edit(c=>c.chapters.push({title:"New draft chapter",lessons:[structuredClone(lesson)]}));setCi(content.chapters.length);setLi(0);}}>{t("افزودن فصل","Add chapter","Kapitel hinzufügen","Bölüm ekle")}</button><button type="button" className={button} disabled={content.chapters.length<=3} onClick={()=>{edit(c=>c.chapters.splice(ci,1));setCi(0);setLi(0);}}>{t("حذف فصل از پیش‌نویس","Remove draft chapter","Entwurfskapitel entfernen","Taslak bölümü kaldır")}</button></div>
 <label className="block">{t("عنوان درس","Lesson title","Lektionstitel","Ders başlığı")}<input className={field} value={lesson.title} onChange={e=>edit(c=>{c.chapters[ci].lessons[li].title=e.target.value;})}/></label><label className="block">{t("خلاصهٔ درس","Lesson summary","Zusammenfassung","Ders özeti")}<textarea className={field} rows={4} value={lesson.content} onChange={e=>edit(c=>{c.chapters[ci].lessons[li].content=e.target.value;})}/></label><label className="block">{t("تمرین عملی","Practice task","Praktische Übung","Pratik görev")}<textarea className={field} value={lesson.activity} onChange={e=>edit(c=>{c.chapters[ci].lessons[li].activity=e.target.value;})}/></label>
 <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={li===0} onClick={()=>{edit(c=>move(c.chapters[ci].lessons,li,-1));setLi(li-1);}}>↑ {t("درس","Lesson","Lektion","Ders")}</button><button type="button" className={button} disabled={li===chapter.lessons.length-1} onClick={()=>{edit(c=>move(c.chapters[ci].lessons,li,1));setLi(li+1);}}>↓ {t("درس","Lesson","Lektion","Ders")}</button><button type="button" className={button} disabled={chapter.lessons.length>=8} onClick={()=>{edit(c=>c.chapters[ci].lessons.push({...structuredClone(lesson),title:"New draft lesson"}));setLi(chapter.lessons.length);}}>{t("افزودن درس","Add lesson","Lektion hinzufügen","Ders ekle")}</button><button type="button" className={button} disabled={chapter.lessons.length<=1} onClick={()=>{edit(c=>c.chapters[ci].lessons.splice(li,1));setLi(0);}}>{t("حذف درس از پیش‌نویس","Remove draft lesson","Entwurfslektion entfernen","Taslak dersi kaldır")}</button></div>
 {lesson.blocks?.map((b,i)=><details key={`${ci}:${li}:${i}`} className="rounded-xl border border-slate-500/30 p-4"><summary className="cursor-pointer">{i+1}. {b.type}</summary><div className="mt-3 space-y-3">{b.type==="image"&&<AcademyImageUpload onUploaded={url=>edit(c=>{Object.assign(c.chapters[ci].lessons[li].blocks![i],{url});})}/>} {Object.entries(b).filter(([k])=>k!=="type").map(([k,v])=><label key={k} className="block">{k}<textarea className={field} dir={k==="code"||k==="url"?"ltr":undefined} value={Array.isArray(v)?JSON.stringify(v):v} onChange={e=>{let value:unknown=e.target.value;if(Array.isArray(v)){try{value=JSON.parse(e.target.value);}catch{return;}}edit(c=>{Object.assign(c.chapters[ci].lessons[li].blocks![i],{[k]:value});});}}/></label>)}<div className="flex gap-2"><button type="button" className={button} disabled={i===0} onClick={()=>edit(c=>move(c.chapters[ci].lessons[li].blocks!,i,-1))}>↑</button><button type="button" className={button} disabled={i===lesson.blocks!.length-1} onClick={()=>edit(c=>move(c.chapters[ci].lessons[li].blocks!,i,1))}>↓</button><button type="button" className={button} disabled={lesson.blocks!.length<=2} onClick={()=>edit(c=>{c.chapters[ci].lessons[li].blocks!.splice(i,1);})}>{t("حذف بلوک","Remove block","Block entfernen","Bloğu kaldır")}</button></div></div></details>)}
 <div className="flex flex-wrap gap-2"><select aria-label="New block type" className={field+" max-w-xs"} value={blockType} onChange={e=>setBlockType(e.target.value)}>{["heading","paragraph","keyConcept","definition","example","code","codeExplanation","steps","callout","warning","tip","quote","formula","reflection","summary","flashcards","table","image","knowledgeCheck"].map(v=><option key={v}>{v}</option>)}</select><button type="button" className={button} disabled={(lesson.blocks?.length||0)>=80} onClick={addBlock}>{t("افزودن بلوک","Add block","Block hinzufügen","Blok ekle")}</button></div>
 <p className="text-sm text-slate-400">{t("این تغییرها پیش‌نویس هستند؛ قبل از انتشار ذخیره و بازبینی کن.","These edits are drafts. Save and review before publishing.","Änderungen sind Entwürfe. Vor Veröffentlichung speichern und prüfen.","Bu düzenlemeler taslaktır. Yayınlamadan önce kaydet ve incele.")}</p>
 </fieldset>;
}
