import {NextRequest,NextResponse} from "next/server";
import {requireAuth,unauthorizedResponse} from "@/lib/auth/middleware";
import {studentWorkspaceDisabledResponse} from "@/lib/student/access";
import {prisma} from "@/lib/db/prisma";
import {z} from "zod";
export const dynamic="force-dynamic";
const schema=z.object({majorId:z.string().max(100).nullable(),specializationId:z.string().max(100).nullable().optional(),educationLevel:z.string().max(100).default(""),institution:z.string().max(250).default(""),faculty:z.string().max(250).default(""),academicYear:z.number().int().min(1).max(20).nullable().optional(),expectedGraduationYear:z.number().int().min(2000).max(2100).nullable().optional(),interests:z.array(z.string().max(100)).max(30).default([]),learningGoals:z.string().max(3000).default("")}).strict();
export async function GET(req:NextRequest){const user=await requireAuth(req);if(!user)return unauthorizedResponse(req);const denied=await studentWorkspaceDisabledResponse(user);if(denied)return denied;const [profile,majors,enrollments,completions]=await Promise.all([prisma.studentAcademicProfile.findUnique({where:{userId:user.id},include:{major:true}}),prisma.academicMajor.findMany({where:{status:"ACTIVE"},include:{specializations:{where:{status:"ACTIVE"}}},orderBy:{name:"asc"}}),prisma.aiCourseProgress.findMany({where:{userId:user.id},include:{course:{select:{title:true}}},orderBy:{updatedAt:"desc"}}),prisma.aiCourseCompletion.findMany({where:{userId:user.id},include:{certificate:true},orderBy:{completedAt:"desc"}})]);const versions=await prisma.aiCourseVersion.findMany({where:{id:{in:enrollments.flatMap(e=>e.versionId?[e.versionId]:[])}},select:{id:true,title:true}});return NextResponse.json({profile,majors,enrollments:enrollments.map(e=>({...e,course:{title:versions.find(v=>v.id===e.versionId)?.title||e.course.title}})),completions},{headers:{"Cache-Control":"private, no-store"}});}
export async function PATCH(req:NextRequest){const user=await requireAuth(req);if(!user)return unauthorizedResponse(req);const denied=await studentWorkspaceDisabledResponse(user);if(denied)return denied;const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"INVALID_ACADEMIC_PROFILE"},{status:400});const data=parsed.data;if(data.majorId&&!await prisma.academicMajor.findFirst({where:{id:data.majorId,status:"ACTIVE"}}))return NextResponse.json({error:"INVALID_MAJOR"},{status:400});if(data.specializationId&&!await prisma.academicSpecialization.findFirst({where:{id:data.specializationId,majorId:data.majorId||"",status:"ACTIVE"}}))return NextResponse.json({error:"INVALID_SPECIALIZATION"},{status:400});const payload={...data,specializationId:data.specializationId||null,interests:JSON.stringify(data.interests)};const profile=await prisma.studentAcademicProfile.upsert({where:{userId:user.id},create:{userId:user.id,...payload},update:payload});return NextResponse.json({profile});}
