export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { routedStreamChat } from "@/lib/ai/router";
import { isCronAuthorized } from "@/lib/auth/cronAuth";

// Hit by a system crontab entry, same shared-secret pattern as
// cron/crm-automation and cron/instagram-publish.
//
// Phase 2 of the real-automation pass: the "Viewing Coordinator" module only
// ever reminded the owner to go type up their own follow-up message by hand
// -- this is what actually drafts it. A viewing marked "completed" with no
// feedback recorded after FOLLOWUP_DELAY_HOURS gets an AI-written follow-up
// message attached to a CrmTask as `draftMessage`. Nothing is sent
// automatically: the owner reviews and sends it themselves from the task
// (Draft-and-Approve, per the project's locked decision on outbound
// messages) -- this only saves the minutes spent composing it from scratch.
const FOLLOWUP_DELAY_HOURS = 24;

export async function GET(req: NextRequest) {
  if (!isCronAuthorized(req)) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const threshold = new Date(Date.now() - FOLLOWUP_DELAY_HOURS * 60 * 60 * 1000);

  const viewings = await prisma.propertyViewing.findMany({
    where: { status: "completed", feedback: null, updatedAt: { lte: threshold } },
    include: {
      contact: { select: { id: true, name: true } },
      property: { select: { title: true, address: true } },
    },
  });

  let drafted = 0;
  const errors: string[] = [];

  for (const v of viewings) {
    if (!v.contactId || !v.contact) continue; // nothing to follow up with
    try {
      const title = `پیگیری بازدید: ${v.contact.name} — ${v.property.title}`;
      const existing = await prisma.crmTask.findFirst({ where: { userId: v.userId, contactId: v.contactId, title } });
      if (existing) continue; // already drafted for this exact viewing

      let draft = "";
      await routedStreamChat(
        [{
          role: "user",
          content: `یک پیام پیگیری کوتاه و دوستانه (۲ تا ۴ جمله، فارسی) برای ${v.contact.name} بنویس که به‌تازگی از ملک «${v.property.title}» (${v.property.address}) بازدید کرده و هنوز بازخوردی نداده است. لحن باید حرفه‌ای و بدون فشار باشد؛ فقط بپرس نظرش چیست و آیا سوالی دارد.`,
        }],
        "تو دستیار یک مشاور املاک هستی و پیام‌های پیگیری مشتری را می‌نویسی.",
        (chunk) => { draft += chunk; },
        () => {}
      );
      draft = draft.trim();
      if (!draft) continue;

      await prisma.crmTask.create({
        data: { userId: v.userId, contactId: v.contactId, title, autoGenerated: true, draftMessage: draft },
      });
      drafted++;
    } catch (err) {
      errors.push(`viewing ${v.id}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return NextResponse.json({ viewingsChecked: viewings.length, drafted, errors });
}
