import { prisma } from "@/lib/db/prisma";
import { getCrmTemplate } from "@/lib/crm/industryTemplates";
import { createInvoiceWithNumber } from "@/lib/repositories/crmInvoiceRepository";

/**
 * Centralizes the CRM write paths that need more than a plain userId-scoped
 * CRUD — pipeline seeding from an industry template, and moving a deal
 * between stages (which must verify the target stage actually belongs to
 * the deal's own pipeline, not just to the user, or a deal could be dropped
 * into another pipeline's stage by ID guessing).
 */

export function createPipelineFromTemplate(userId: string, industrySlug: string | null, isDefault: boolean, businessId?: string | null) {
  const template = getCrmTemplate(industrySlug);
  return prisma.crmPipeline.create({
    data: {
      userId,
      ...(businessId ? { businessId } : {}),
      name: template.pipelineName,
      nameEn: template.pipelineNameEn,
      nameDe: template.pipelineNameDe,
      industrySlug: industrySlug || undefined,
      isDefault,
      stages: {
        create: template.stages.map((s, i) => ({
          name: s.name,
          nameEn: s.nameEn,
          nameDe: s.nameDe,
          order: i,
          isWon: s.isWon ?? false,
          isLost: s.isLost ?? false,
        })),
      },
    },
    include: { stages: { orderBy: { order: "asc" } } },
  });
}

/**
 * Verifies the deal, and the target stage, both belong to this user before
 * moving. Landing on an isWon stage auto-advances the linked contact's
 * lifecycle to "customer" (only moving it forward, never backward — a
 * contact that's already a customer stays one even if a later deal is lost).
 * Landing on an isLost stage accepts an optional reason, since a deal falling
 * through needs to be recorded, not just silently vanish from the board.
 */
export async function moveDealToStage(userId: string, dealId: string, stageId: string, lostReason?: string, businessId?: string | null) {
  const businessScope = businessId ? { businessId } : {};
  const deal = await prisma.crmDeal.findFirst({ where: { id: dealId, userId, ...businessScope } });
  if (!deal) return null;

  const stage = await prisma.crmStage.findFirst({
    where: { id: stageId, pipelineId: deal.pipelineId },
  });
  if (!stage) return null;

  const updated = await prisma.crmDeal.update({
    where: { id: dealId },
    data: {
      stageId,
      status: stage.isWon ? "won" : stage.isLost ? "lost" : "open",
      wonAt: stage.isWon ? new Date() : null,
      lostReason: stage.isLost ? (lostReason || undefined) : undefined,
    },
  });

  if (stage.isWon) {
    await prisma.crmContact.updateMany({
      where: { id: deal.contactId, ...businessScope, status: { in: ["lead", "qualified"] } },
      data: { status: "customer" },
    });

    // Sales-chain phase 2.5: winning a deal used to update the pipeline and
    // stop there -- accounting and any other interested lead only found out
    // if the owner remembered to tell them. Both of the two closures below
    // are additive and reversible (a draft invoice, a pending commission
    // record, an internal task) -- nothing here bills or messages anyone
    // automatically.
    await autoCreateInvoiceDraftForWonDeal(userId, deal.id, deal.title, deal.value, deal.contactId, deal.commissionRate, deal.commissionAmount, businessId);
    await notifyOtherInterestedLeads(userId, deal.id, deal.contactId, businessId);
  }

  // Event-driven CRM automation, phase 2: a deal moving stages used to
  // require the owner to remember to act on it themselves -- the only
  // existing automation (cron/crm-automation) is time-based (stale/no
  // activity), not triggered by the move itself. A deal landing on any
  // open (non-won, non-lost) stage past the first one now creates a
  // reminder task right here, at the moment it happens. Deliberately just
  // an internal task, never an outbound message -- nothing here contacts
  // the lead, so it needs no draft/approve step.
  if (!stage.isWon && !stage.isLost) {
    const firstStage = await prisma.crmStage.findFirst({ where: { pipelineId: deal.pipelineId }, orderBy: { order: "asc" } });
    if (firstStage && firstStage.id !== stage.id) {
      const title = `پیگیری: معامله «${deal.title}» به مرحله «${stage.name}» رسید`;
      const alreadyExists = await prisma.crmTask.findFirst({ where: { userId, ...businessScope, contactId: deal.contactId, title, status: "pending" } });
      if (!alreadyExists) {
        await prisma.crmTask.create({ data: { userId, ...(businessId ? { businessId } : {}), contactId: deal.contactId, title, autoGenerated: true } });
      }
    }
  }

  return updated;
}

/**
 * Sales-chain phase 2.5, leak #2: winning a deal used to leave billing
 * entirely to the owner remembering to open Accounting themselves. This
 * creates a DRAFT invoice (never sent) for the deal's own value, and --
 * only if the deal actually has a commission rate/amount set -- a pending
 * commission record. Both still need a human to review/send/pay; nothing
 * here moves money or reaches the customer on its own.
 */
async function autoCreateInvoiceDraftForWonDeal(
  userId: string, dealId: string, dealTitle: string, dealValue: number, contactId: string,
  commissionRate: number | null, commissionAmount: number | null, businessId?: string | null
) {
  try {
    const existing = await prisma.crmInvoice.findFirst({ where: { userId, ...(businessId ? { businessId } : {}), dealId } });
    if (!existing && dealValue > 0) {
      await createInvoiceWithNumber(userId, {
        ...(businessId ? { businessId } : {}),
        contact: { connect: { id: contactId } },
        deal: { connect: { id: dealId } },
        status: "draft",
        subtotal: dealValue,
        total: dealValue,
        notes: `پیش‌نویس خودکار — ایجادشده هنگام برد معامله «${dealTitle}»`,
        items: { create: [{ description: dealTitle, quantity: 1, unitPrice: dealValue, lineTotal: dealValue }] },
      });
    }
  } catch (err) {
    // Never let a billing-side hiccup roll back the pipeline move itself --
    // the deal is still won either way; a missing draft invoice is
    // recoverable by hand, a rolled-back win is not.
    console.error("autoCreateInvoiceDraftForWonDeal failed:", err);
  }

  const amount = commissionAmount ?? (commissionRate ? dealValue * (commissionRate / 100) : null);
  if (amount && amount > 0) {
    try {
      const existingCommission = await prisma.accountingCommissionRecord.findFirst({ where: { dealId } });
      if (!existingCommission) {
        await prisma.accountingCommissionRecord.create({
          data: {
            workspaceUserId: userId,
            dealId,
            totalAmount: amount,
            splits: { create: [{ agentUserId: userId, percent: 100, amount }] },
          },
        });
      }
    } catch (err) {
      console.error("autoCreateCommissionRecord failed:", err);
    }
  }
}

/**
 * Sales-chain phase 2.5, leak #3: a property/item selling used to leave
 * every OTHER lead who'd shown interest in it with no idea it's gone --
 * they'd only find out by asking. This creates one internal task per other
 * interested contact (Draft-and-Approve: an internal reminder to tell them,
 * not a message sent on their behalf).
 */
async function notifyOtherInterestedLeads(userId: string, dealId: string, winningContactId: string, businessId?: string | null) {
  try {
    const scope = businessId ? { businessId } : {};
    const property = await prisma.property.findFirst({ where: { crmDealId: dealId, ...scope } });
    if (!property) return;

    const otherInterests = await prisma.propertyInterest.findMany({
      where: { propertyId: property.id, ...scope, contactId: { not: winningContactId } },
      include: { contact: { select: { id: true, name: true } } },
    });

    for (const interest of otherInterests) {
      const title = `اطلاع‌رسانی: ملک «${property.title}» فروخته شد — به ${interest.contact.name} بگویید و ملک مشابه پیشنهاد دهید`;
      const alreadyExists = await prisma.crmTask.findFirst({ where: { userId, ...scope, contactId: interest.contactId, title } });
      if (!alreadyExists) {
        await prisma.crmTask.create({ data: { userId, ...(businessId ? { businessId } : {}), contactId: interest.contactId, title, autoGenerated: true } });
      }
    }
  } catch (err) {
    console.error("notifyOtherInterestedLeads failed:", err);
  }
}

export async function countUserContacts(userId: string, businessId?: string | null): Promise<number> {
  return prisma.crmContact.count({ where: { userId, ...(businessId ? { businessId } : {}) } });
}
