"use client";
import { useEffect,useState,useCallback } from "react";
import { useTranslation,tri } from "@/lib/i18n";
import Link from "next/link";
type Payment={id:string;plan:string;status:string;transferCurrency:string;transferMinor:number;bankSnapshot:string;receiptAt:string|null;reviewNote:string|null};
export default function Checkout({params}:{params:{id:string}}){
 const {lang}=useTranslation();const [p,setP]=useState<Payment|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const text=(fa:string,en:string,de:string,tr:string)=>tri(lang,fa,en,de,tr);
 const load=useCallback(async()=>{const r=await fetch(`/api/payment/${params.id}`);const d=await r.json();if(!r.ok)setError(d.error);else setP(d.payment);},[params.id]);
 useEffect(()=>{void load();},[load]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`/api/payment/${params.id}/receipt`,{method:"POST",body:new FormData(e.currentTarget)});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Error");}finally{setBusy(false);}}
 const bank=p?JSON.parse(p.bankSnapshot):{};
 const planName=p?.plan==="STUDENT_FIRST_TWO_MONTHS"?text("آفر اولین اشتراک دانشجویی","Student welcome offer","Studierenden-Willkommensangebot","Öğrenci hoş geldin teklifi"):p?.plan.startsWith("STUDENT_")?text("اشتراک دانشجویی ماهانه","Monthly student subscription","Monatliches Studierendenabo","Aylık öğrenci aboneliği"):p?.plan.startsWith("CRM_")?text("اشتراک مدیریت مشتری","CRM subscription","CRM-Abonnement","CRM aboneliği"):p?.plan.startsWith("CREDITS_")?text("خرید اعتبار AI","AI credit top-up","KI-Guthaben aufladen","Yapay zekâ kredisi yükleme"):text("اشتراک AI تیم","Team AI subscription","Team-KI-Abonnement","Ekip yapay zekâ aboneliği");
 return <main className="max-w-2xl mx-auto p-6 space-y-5"><h1 className="text-2xl font-bold">{text("پرداخت بانکی","Bank transfer","Banküberweisung","Banka havalesi")}</h1>{error&&<p role="alert" className="text-red-500">{error}</p>}{p&&<><p>{planName}</p><p className="text-3xl font-bold" dir="ltr">{(p.transferMinor/100).toLocaleString(lang,{minimumFractionDigits:2})} {p.transferCurrency}</p><div className="border rounded-xl p-5 space-y-3"><p>{text("صاحب حساب","Account holder","Kontoinhaber","Hesap sahibi")}: <b dir="ltr">{bank.holder}</b></p><p dir="ltr" className="break-all">IBAN: {bank.iban}</p><p>{text("شناسه سفارش","Order reference","Bestellreferenz","Sipariş referansı")}: {p.id}</p></div><p>{text("مبلغ دقیق را به حساب بالا منتقل کنید و رسید را بارگذاری کنید. اشتراک پس از بررسی و تأیید ادمین فعال می‌شود؛ آپلود رسید به معنی تأیید پرداخت نیست.","Transfer the exact amount and upload your receipt. Your subscription activates after admin approval. Uploading a receipt does not confirm payment.","Überweisen Sie den genauen Betrag und laden Sie den Beleg hoch. Das Abo wird nach Freigabe durch den Administrator aktiviert.","Tam tutarı havale edip dekontu yükleyin. Aboneliğiniz yönetici onayından sonra etkinleşir; dekont yüklemek ödeme onayı değildir.")}</p>{p.transferCurrency==="EUR"&&<p>{text("فقط انتقال از زراعت‌بانک به زراعت‌بانک؛ بدون کمیسیون.","Ziraat Bank to Ziraat Bank transfers only; no commission.","Nur Überweisungen von Ziraat Bank zu Ziraat Bank; ohne Provision.","Yalnızca Ziraat Bank'tan Ziraat Bank'a transfer; komisyonsuz.")}</p>}{p.status==="PENDING"&&!p.receiptAt?<form onSubmit={upload} className="space-y-4"><label className="block">{text("رسید پرداخت: JPG، PNG یا PDF، حداکثر ۵ مگابایت","Payment receipt: JPG, PNG or PDF, maximum 5 MB","Zahlungsbeleg: JPG, PNG oder PDF, maximal 5 MB","Ödeme dekontu: JPG, PNG veya PDF, en fazla 5 MB")}<input required name="receipt" type="file" accept="image/jpeg,image/png,application/pdf" className="block mt-3" /></label><button disabled={busy} className="bg-orange-600 text-white px-6 py-3 rounded-xl">{busy?"…":text("ارسال رسید","Submit receipt","Beleg senden","Dekont gönder")}</button></form>:<div role="status"><p>{p.status==="SUCCESS"?text("پرداخت تأیید شد؛ اشتراک فعال است.","Payment approved; subscription active.","Zahlung bestätigt; Abo aktiv.","Ödeme onaylandı; abonelik etkin."):p.status==="REJECTED"?text("رسید رد شده است.","Receipt rejected.","Beleg abgelehnt.","Dekont reddedildi."):text("رسید ثبت شد و منتظر بررسی ادمین است.","Receipt submitted, awaiting admin review.","Beleg eingereicht, Prüfung ausstehend.","Dekont alındı; yönetici incelemesi bekleniyor.")}</p>{p.reviewNote&&<p>{p.reviewNote}</p>}{p.receiptAt&&<a href={`/api/payment/${p.id}/receipt`}>{text("دانلود رسید","Download receipt","Beleg herunterladen","Dekont indir")}</a>}</div>}</>}<Link href="/settings">{text("تاریخچه حساب","Account history","Kontoverlauf","Hesap geçmişi")}</Link></main>;
}
