import type { Copy } from "@/lib/marketing/catalog";
export type ModuleGuide = { path: string; purpose: Copy; links: string[] };
export const moduleGuides: ModuleGuide[] = [
  { path: "/home", purpose: ["از اینجا کار امروز را انتخاب کنید و به فضای مرتبط بروید.", "Choose today's work and open the relevant workspace.", "Heutige Aufgabe wählen und den passenden Bereich öffnen.", "Bugünkü işinizi seçip ilgili çalışma alanını açın."], links: ["/agents", "/chat"] },
  { path: "/crm", purpose: ["مشتری، معامله و پیگیری بعدی را در یک مسیر نگه دارید.", "Keep customers, deals and next follow-ups in one workflow.", "Kunden, Geschäfte und nächste Schritte in einem Ablauf verwalten.", "Müşterileri, fırsatları ve sonraki takipleri tek akışta yönetin."], links: ["/sales", "/lead-gen"] },
  { path: "/sales", purpose: ["ابتدا اطلاعات CRM را کامل کنید، سپس تحلیل یا پیش‌نویس پیگیری بسازید.", "Complete your CRM data, then request analysis or follow-up drafts.", "CRM-Daten vervollständigen, dann Analyse oder Follow-up-Entwürfe erstellen.", "Önce CRM verilerini tamamlayın, sonra analiz veya takip taslağı oluşturun."], links: ["/crm", "/ceo"] },
  { path: "/voice-agent", purpose: ["دستیار را تنظیم کنید و اتصال تماس را پیش از استفادهٔ واقعی بررسی کنید.", "Configure your assistant and check the calling connection before live use.", "Assistent konfigurieren und Telefonverbindung vor echten Anrufen prüfen.", "Asistanı ayarlayıp gerçek kullanım öncesi arama bağlantısını kontrol edin."], links: ["/crm", "/industry"] },
  { path: "/social", purpose: ["برند، محتوا و اتصال حساب را آماده کنید؛ پیش‌نویس را پیش از انتشار بررسی کنید.", "Prepare your brand, content and account connection. Review drafts before publishing.", "Marke, Inhalte und Kontoverbindung vorbereiten. Entwürfe vor Veröffentlichung prüfen.", "Marka, içerik ve hesap bağlantısını hazırlayın. Yayınlamadan önce taslağı inceleyin."], links: ["/image/generate", "/seo"] },
  { path: "/lead-gen", purpose: ["یک فرم بسازید، لینک را به اشتراک بگذارید و سرنخ‌ها را در CRM دنبال کنید.", "Build a form, share its link and follow leads in CRM.", "Formular erstellen, Link teilen und Leads im CRM verfolgen.", "Form oluşturup bağlantısını paylaşın ve aday müşterileri CRM'de takip edin."], links: ["/crm", "/social"] },
  { path: "/seo", purpose: ["سایت را بررسی کنید؛ از یافته‌ها به برنامهٔ محتوا و انتشار برسید.", "Audit your site, then turn findings into a content and publishing plan.", "Website prüfen und Ergebnisse in einen Inhalts- und Veröffentlichungsplan umsetzen.", "Siteyi inceleyip bulguları içerik ve yayın planına dönüştürün."], links: ["/seo/sites", "/seo/agent-pipeline"] },
  { path: "/website-designer", purpose: ["هدف و بخش‌های سایت را مشخص کنید؛ خروجی را در پیش‌نمایش و کد بررسی کنید.", "Define the site goal and sections, then review the preview and code.", "Ziel und Bereiche der Website festlegen, dann Vorschau und Code prüfen.", "Site hedefini ve bölümlerini belirleyip önizlemeyi ve kodu inceleyin."], links: ["/seo", "/image/generate"] },
  { path: "/accounting", purpose: ["از ثبت سند و هزینه شروع کنید؛ سپس بانک و گزارش‌ها را بررسی کنید.", "Start with entries and expenses, then review banking and reports.", "Mit Buchungen und Ausgaben beginnen, dann Bankdaten und Berichte prüfen.", "Kayıt ve giderlerle başlayıp banka işlemlerini ve raporları inceleyin."], links: ["/accounting/expenses", "/accounting/assistant"] },
  { path: "/business-doctor", purpose: ["مشخصات واقعی کسب‌وکار را وارد کنید تا پیشنهادها به شرایط شما مرتبط باشند.", "Add accurate business information so recommendations match your situation.", "Korrekte Unternehmensdaten eingeben, damit Empfehlungen zu Ihrer Situation passen.", "Önerilerin durumunuza uygun olması için doğru işletme bilgilerini girin."], links: ["/ceo", "/meeting"] },
  { path: "/ceo", purpose: ["هدف، محدودیت و سؤال تصمیم‌گیری را روشن بیان کنید.", "Clearly describe your goal, constraints and decision question.", "Ziel, Einschränkungen und Entscheidungsfrage klar beschreiben.", "Hedefi, sınırları ve karar sorunuzu açıkça belirtin."], links: ["/ceo/orchestrator", "/business-doctor"] },
  { path: "/meeting", purpose: ["موضوع و اعضای جلسه را انتخاب کنید؛ نتیجه و اقدامات پیشنهادی را بررسی کنید.", "Choose the topic and participants, then review conclusions and suggested actions.", "Thema und Teilnehmer wählen, dann Ergebnisse und vorgeschlagene Schritte prüfen.", "Konu ve katılımcıları seçip sonuçları ve önerilen adımları inceleyin."], links: ["/ceo", "/agents"] },
  { path: "/agents", purpose: ["ایجنت مناسب هدف خود را انتخاب کنید؛ هر ایجنت شما را به فضای تخصصی می‌برد.", "Choose an agent for your goal. Each opens its specialist workspace.", "Passenden Agenten wählen. Jeder öffnet seinen Fachbereich.", "Hedefinize uygun ajanı seçin. Her ajan uzmanlık alanını açar."], links: ["/industry", "/business-doctor"] },
  { path: "/startup/builder", purpose: ["ایده را به برنامه تبدیل کنید، نتیجه را بررسی کنید و برای اجرا تصمیم بگیرید.", "Turn an idea into a plan, review it and decide how to implement it.", "Idee in einen Plan verwandeln, prüfen und Umsetzung entscheiden.", "Fikri plana dönüştürüp inceleyin ve uygulama adımına karar verin."], links: ["/startup/contact", "/business-doctor"] },
  { path: "/image/gallery", purpose: ["خروجی‌های ذخیره‌شده را مرور کنید و برای ساخت جدید به ابزار تولید بروید.", "Review saved outputs or open a generator to create something new.", "Gespeicherte Ergebnisse prüfen oder neue Inhalte erstellen.", "Kaydedilen çıktıları inceleyin veya yeni içerik oluşturun."], links: ["/image/generate", "/video/generate"] },
];
export function findModuleGuide(path: string) {
  return [...moduleGuides].sort((a, b) => b.path.length - a.path.length).find(guide => path === guide.path || path.startsWith(guide.path + "/"));
}
